const API=(window.TICKETORA_API_URL||'').replace(/\/$/,'');
let data={organizers:[],events:[],payments:[],payouts:[],withdrawals:[]};
const $=id=>document.getElementById(id);
async function api(path,o={}){const r=await fetch(`${API}${path}`,{credentials:'include',...o,headers:{'Content-Type':'application/json',...(o.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.message||'Erreur serveur');return d;}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function fmt(n){return Number(n||0).toLocaleString('fr-FR');}
function toast(m,error=false){const c=$('toast-container');if(!c)return;const e=document.createElement('div');e.className=`px-4 py-3 rounded-xl shadow-lg text-sm font-semibold ${error?'bg-rose-600':'bg-navy-900'} text-white`;e.innerText=m;c.appendChild(e);setTimeout(()=>e.remove(),3000);}
function switchTab(t){['overview','events','organizers','payments','scanner','tickets','users','chat','cagnottes','logs','settings'].forEach(x=>{document.getElementById(`tab-${x}`)?.classList.toggle('hidden',x!==t);document.getElementById(`nav-${x}`)?.classList.toggle('active',x===t);});if(t==='chat')loadAdminChat();if(t==='tickets'||t==='users'||t==='logs'||t==='cagnottes')loadAdminExtra(t);if(t!=='scanner'&&t!=='chat'&&t!=='tickets'&&t!=='users'&&t!=='logs')refreshAdminData();}
function openModal(id){$(id)?.classList.remove('hidden')} function closeModal(id){$(id)?.classList.add('hidden')}
function filterAdminData(){const q=($('global-search-input')?.value||'').toLowerCase();document.querySelectorAll('#admin-events-list tr,#admin-org-list tr').forEach(r=>r.classList.toggle('hidden',!r.innerText.toLowerCase().includes(q)));}
function showAdminLogin(){if($('admin-login-overlay'))return;const d=document.createElement('div');d.id='admin-login-overlay';d.className='fixed inset-0 bg-slate-900/95 backdrop-blur-sm z-[100] flex items-center justify-center p-4';d.innerHTML=`<div class="bg-white w-full max-w-md rounded-2xl p-7 shadow-2xl"><div class="text-center mb-6"><img src="logo.png" class="w-14 h-14 mx-auto rounded-xl object-contain"><h2 class="text-2xl font-black text-navy-900 mt-3">Connexion Admin</h2><p class="text-sm text-slate-500">Accès sécurisé au tableau de bord Ticketora</p></div><form id="admin-login-form" class="space-y-4"><input id="admin-login-email" type="email" required value="ticketora2026@gmail.com" class="w-full p-3 bg-slate-50 border rounded-xl"><input id="admin-login-password" type="password" required placeholder="Mot de passe" class="w-full p-3 bg-slate-50 border rounded-xl"><div id="admin-login-error" class="hidden text-sm text-rose-600 font-semibold"></div><button class="w-full bg-brand-orange hover:bg-brand-orangeDark text-white font-bold py-3 rounded-xl">Se connecter</button></form></div>`;document.body.appendChild(d);$('admin-login-form').onsubmit=loginAdmin;}
async function loginAdmin(e){e.preventDefault();try{await api('/api/admin/login',{method:'POST',body:JSON.stringify({email:$('admin-login-email').value,password:$('admin-login-password').value})});$('admin-login-overlay')?.remove();await refreshAdminData();toast('Connexion réussie');}catch(err){$('admin-login-error').innerText=err.message;$('admin-login-error').classList.remove('hidden');}}
async function ensureAdmin(){try{await api('/api/admin/me');return true}catch{showAdminLogin();return false;}}
function renderOrganizers(){const el=$('admin-org-list');if(!el)return;el.innerHTML=data.organizers.map(o=>`<tr class="border-b text-sm"><td class="p-4 font-bold">${esc(o.nom)} ${esc(o.prenom)}</td><td class="p-4 text-slate-500">${esc(o.email)}<br><span class="text-xs">${esc(o.phone)}</span></td><td class="p-4">${fmt(o.event_count)}</td><td class="p-4">${fmt(o.tickets_sold)}</td><td class="p-4 font-bold">${fmt(o.revenue)} FCFA</td><td class="p-4"><span class="px-2 py-1 rounded text-[10px] font-bold ${o.status==='VALIDE'?'bg-emerald-100 text-emerald-700':o.status==='REFUSE'?'bg-red-100 text-red-700':'bg-amber-100 text-amber-700'}">${esc(o.status)}</span></td><td class="p-4 text-right whitespace-nowrap">${o.status==='EN_ATTENTE'?`<button onclick="adminApproveOrg(${o.id})" class="text-xs bg-emerald-600 text-white px-2 py-1 rounded font-bold">Valider</button><button onclick="adminRejectOrg(${o.id})" class="text-xs bg-red-600 text-white px-2 py-1 rounded font-bold ml-1">Refuser</button>`:''}<button onclick="adminDeleteOrg(${o.id})" class="text-xs bg-slate-100 text-red-600 px-2 py-1 rounded font-bold ml-1">Supprimer</button></td></tr>`).join('')||'<tr><td colspan="7" class="p-6 text-center text-slate-400">Aucun organisateur.</td></tr>';}
function renderEvents(){const el=$('admin-events-list');if(!el)return;el.innerHTML=data.events.map(e=>`<tr class="border-b text-sm"><td class="p-4"><div class="flex items-center gap-3">${e.image_url?`<img src="${esc(e.image_url)}" class="w-12 h-12 rounded-lg object-cover border">`:''}<div><span class="font-bold">${esc(e.title)}</span><br><span class="text-xs text-slate-400">${esc(e.organizer_name||'Ticketora')}</span></div></div></td><td class="p-4">${esc(e.category)}</td><td class="p-4">${fmt(e.price)} FCFA</td><td class="p-4">${fmt(e.capacity)}<br><span class="text-xs text-slate-400">${fmt(e.sold_count)} vendus</span></td><td class="p-4"><span class="px-2 py-1 rounded text-[10px] font-bold ${e.status==='PUBLIE'?'bg-emerald-100 text-emerald-700':e.status==='REFUSE'?'bg-red-100 text-red-700':'bg-amber-100 text-amber-700'}">${esc(e.status)}</span></td><td class="p-4 text-right">${e.status!=='PUBLIE'?`<button onclick="adminSetEventStatus(${e.id},'PUBLIE')" class="text-xs bg-emerald-600 text-white px-2 py-1 rounded font-bold">Valider</button>`:''}${e.status!=='REFUSE'?`<button onclick="adminSetEventStatus(${e.id},'REFUSE')" class="text-xs bg-red-600 text-white px-2 py-1 rounded font-bold ml-1">Refuser</button>`:''}<button onclick="adminDeleteEvent(${e.id})" class="text-xs bg-slate-200 text-red-600 px-2 py-1 rounded font-bold ml-1"><i class="fa-solid fa-trash"></i></button></td></tr>`).join('')||'<tr><td colspan="6" class="p-6 text-center text-slate-400">Aucun événement.</td></tr>';}
function renderPayments(){const el=$('admin-payments-list');if(!el)return;el.innerHTML=data.payments.map(t=>`<tr class="border-b text-sm"><td class="p-4 font-mono font-bold">${esc(t.code)}</td><td class="p-4">${esc(t.customer_name)}<br><span class="text-xs text-slate-400">${esc(t.customer_email)}</span></td><td class="p-4">${esc(t.event_title)}</td><td class="p-4 font-bold">${fmt(t.total_amount)} FCFA</td><td class="p-4 text-emerald-600 font-bold">${fmt(t.admin_commission)} FCFA</td><td class="p-4">${esc(t.created_at||'')}</td></tr>`).join('')||'<tr><td colspan="6" class="p-6 text-center text-slate-400">Aucune transaction.</td></tr>';}
function statusBadge(status){return `<span class="px-2 py-1 rounded text-[10px] font-bold ${status==='PAYE'?'bg-emerald-100 text-emerald-700':status==='REFUSE'?'bg-red-100 text-red-700':status==='VALIDE'?'bg-blue-100 text-blue-700':'bg-amber-100 text-amber-700'}">${esc(status)}</span>`;}
function downloadPayoutPDF(p){if(!window.jspdf?.jsPDF){toast('Le module PDF n’est pas chargé.',true);return;}const {jsPDF}=window.jspdf;const doc=new jsPDF();doc.setFontSize(20);doc.text('TICKETORA',20,20);doc.setFontSize(14);doc.text('Justificatif de retrait',20,32);doc.setFontSize(11);const lines=[`ID : ${p.id}`,`Organisateur : ${p.nom||''} ${p.prenom||''}`,`Email : ${p.email||''}`,`Compte : ${p.account||''}`,`Montant : ${fmt(p.amount)} FCFA`,`Statut : ${p.status}`,`Date de demande : ${p.created_at||''}`,`Date de traitement : ${p.processed_at||'-'}`];lines.forEach((x,i)=>doc.text(x,20,48+i*10));doc.setFontSize(9);doc.text('Document généré depuis l’espace administrateur Ticketora.',20,145);doc.save(`Retrait_Organisateur_${p.id}.pdf`);}
function renderPayouts(){const el=$('admin-payouts-list');if(!el)return;el.innerHTML=data.payouts.map(p=>`<tr class="border-b text-sm"><td class="p-4 font-bold">${esc(p.nom||'')} ${esc(p.prenom||'')}<br><span class="text-xs text-slate-400">${esc(p.email||'')}</span></td><td class="p-4 font-mono">${esc(p.account)}</td><td class="p-4 font-bold">${fmt(p.amount)} FCFA</td><td class="p-4">${statusBadge(p.status)}</td><td class="p-4 text-xs text-slate-500">${esc(p.created_at||'')}</td><td class="p-4 text-right whitespace-nowrap">${p.status==='EN_ATTENTE'?`<button onclick="adminSetPayoutStatus(${p.id},'VALIDE')" class="text-xs bg-emerald-600 text-white px-2 py-1 rounded font-bold">Valider</button><button onclick="adminSetPayoutStatus(${p.id},'REFUSE')" class="text-xs bg-red-600 text-white px-2 py-1 rounded font-bold ml-1">Refuser</button>`:p.status==='VALIDE'?`<button onclick="adminSetPayoutStatus(${p.id},'PAYE')" class="text-xs bg-blue-600 text-white px-2 py-1 rounded font-bold">Marquer payé</button>`:''}${['VALIDE','PAYE'].includes(p.status)?`<button onclick='downloadPayoutPDF(${JSON.stringify(p).replace(/'/g,"&#39;")})' class="text-xs bg-slate-900 text-white px-2 py-1 rounded font-bold ml-1"><i class="fa-solid fa-file-pdf"></i> PDF</button>`:''}${['EN_ATTENTE','REFUSE'].includes(p.status)?`<button onclick="adminDeletePayout(${p.id})" class="text-xs bg-slate-200 text-red-600 px-2 py-1 rounded font-bold ml-1"><i class="fa-solid fa-trash"></i></button>`:''}</td></tr>`).join('')||'<tr><td colspan="6" class="p-6 text-center text-slate-400">Aucune demande de retrait.</td></tr>';}
function renderAdminWithdrawals(wd){const b=$('admin-withdrawal-balance');if(b)b.innerText=fmt(wd?.balance||0);const el=$('admin-withdrawals-list');if(!el)return;el.innerHTML=(data.withdrawals||[]).map(p=>`<tr class="border-b text-sm"><td class="p-4 font-bold">${fmt(p.amount)} FCFA</td><td class="p-4 font-mono">${esc(p.account)}</td><td class="p-4">${statusBadge(p.status)}</td><td class="p-4 text-xs text-slate-500">${esc(p.created_at||'')}</td><td class="p-4 text-right">${p.status==='EN_ATTENTE'?`<button onclick="adminSetWithdrawalStatus(${p.id},'PAYE')" class="text-xs bg-emerald-600 text-white px-2 py-1 rounded font-bold">Marquer payé</button><button onclick="adminSetWithdrawalStatus(${p.id},'REFUSE')" class="text-xs bg-red-600 text-white px-2 py-1 rounded font-bold ml-1">Refuser</button>`:''}${['EN_ATTENTE','REFUSE'].includes(p.status)?`<button onclick="adminDeleteWithdrawal(${p.id})" class="text-xs bg-slate-200 text-red-600 px-2 py-1 rounded font-bold ml-1"><i class="fa-solid fa-trash"></i></button>`:''}</td></tr>`).join('')||'<tr><td colspan="5" class="p-6 text-center text-slate-400">Aucun retrait admin.</td></tr>';}
async function adminDeletePayout(id){if(!confirm('Supprimer cette demande de retrait ?'))return;try{await api(`/api/admin/payouts/${id}`,{method:'DELETE'});toast('Demande supprimée');await refreshAdminData()}catch(e){toast(e.message,true)}}
async function adminSetPayoutStatus(id,status){if(status==='REFUSE'&&!confirm('Refuser cette demande de retrait ?'))return;try{await api(`/api/admin/payouts/${id}/status`,{method:'POST',body:JSON.stringify({status})});toast(status==='VALIDE'?'Retrait validé':status==='PAYE'?'Retrait marqué comme payé':'Retrait refusé');await refreshAdminData();}catch(e){toast(e.message,true);}}
async function createAdminWithdrawal(e){e.preventDefault();const amount=Number($('admin-withdrawal-amount').value),account=$('admin-withdrawal-account').value.trim();if(!amount||!account)return toast('Montant et compte obligatoires.',true);try{await api('/api/admin/withdrawals',{method:'POST',body:JSON.stringify({amount,account})});$('admin-withdrawal-form').reset();toast('Demande de retrait admin créée');await refreshAdminData();}catch(err){toast(err.message,true);}}
async function adminDeleteWithdrawal(id){if(!confirm('Supprimer ce retrait administrateur ?'))return;try{await api(`/api/admin/withdrawals/${id}`,{method:'DELETE'});toast('Retrait supprimé');await refreshAdminData()}catch(e){toast(e.message,true)}}
async function adminSetWithdrawalStatus(id,status){if(status==='REFUSE'&&!confirm('Refuser ce retrait admin ?'))return;try{await api(`/api/admin/withdrawals/${id}/status`,{method:'POST',body:JSON.stringify({status})});toast(status==='PAYE'?'Retrait admin marqué comme payé':'Retrait admin refusé');await refreshAdminData();}catch(e){toast(e.message,true);}}
async function refreshAdminData(){if(!(await ensureAdmin()))return;try{const [o,e,p,ov,po,wd]=await Promise.all([api('/api/admin/organizers'),api('/api/admin/events'),api('/api/admin/payments'),api('/api/admin/overview'),api('/api/admin/payouts'),api('/api/admin/withdrawals')]);data.organizers=o.organizers||[];data.events=e.events||[];data.payments=p.payments||[];data.payouts=po.payouts||[];data.withdrawals=wd.withdrawals||[];const st=ov.stats||{};$('stat-revenue').innerHTML=`${fmt(st.revenue)} FCFA`;$('stat-tickets').innerText=st.tickets||0;$('stat-events').innerText=st.events||0;if($('stat-users'))$('stat-users').innerText=st.users||0;if($('stat-organizers'))$('stat-organizers').innerText=st.organizers||0;if($('admin-current-date'))$('admin-current-date').innerHTML=`<i class="fa-regular fa-calendar mr-1"></i> ${new Date().toLocaleDateString('fr-FR')}`;if($('badge-org-pending'))$('badge-org-pending').innerText=`${st.pendingOrganizers||0} Attente`;if($('badge-events-count'))$('badge-events-count').innerText=data.events.length;if($('pay-pending'))$('pay-pending').innerText=st.payments?.pending||0;if($('pay-completed'))$('pay-completed').innerText=st.payments?.completed||0;if($('pay-failed'))$('pay-failed').innerText=st.payments?.failed||0;if($('pay-refunded'))$('pay-refunded').innerText=st.payments?.refunded||0;const wp=data.withdrawals.filter(x=>x.status==='EN_ATTENTE').length,wpaid=data.withdrawals.filter(x=>x.status==='PAYE').length,wr=data.withdrawals.filter(x=>x.status==='REFUSE').length;if($('wd-pending'))$('wd-pending').innerText=wp;if($('wd-paid'))$('wd-paid').innerText=wpaid;if($('wd-rejected'))$('wd-rejected').innerText=wr;renderOrganizers();renderEvents();renderPayments();renderPayouts();renderAdminWithdrawals(wd);const el=$('dashboard-events-list');if(el)el.innerHTML=data.events.slice(0,4).map(ev=>`<div class="w-full px-5 py-2 flex justify-between text-[10px]"><span class="font-bold text-white">${esc(ev.title||'Événement')}</span><span class="text-[#8aa1bf]">${esc(ev.date||'')}</span></div>`).join('')||'Aucun événement trouvé';const act=$('dashboard-activity-list');if(act){const sales=ov.sales||[];act.innerHTML=sales.length?sales.slice(0,4).map(t=>`<div class="flex justify-between py-2"><span>${esc(t.customer_name||'Client')} a acheté un billet</span><span class="text-white">${fmt(t.total_amount)} FCFA</span></div>`).join(''):'Aucune activité pour le moment';}renderDashboardCharts();}catch(e){console.error(e);toast(e.message,true);}}
async function adminApproveOrg(id){try{await api(`/api/admin/organizers/${id}/approve`,{method:'POST'});toast('Organisateur validé');refreshAdminData()}catch(e){toast(e.message,true)}}
async function adminRejectOrg(id){if(!confirm('Refuser cette demande ?'))return;try{await api(`/api/admin/organizers/${id}/reject`,{method:'POST'});toast('Demande refusée');refreshAdminData()}catch(e){toast(e.message,true)}}
async function adminDeleteOrg(id){if(!confirm('Supprimer cet organisateur ?'))return;try{await api(`/api/admin/organizers/${id}`,{method:'DELETE'});toast('Organisateur supprimé');refreshAdminData()}catch(e){toast(e.message,true)}}
async function adminDeleteEvent(id){if(!confirm('Supprimer définitivement cet événement ?'))return;try{await api(`/api/admin/events/${id}`,{method:'DELETE'});toast('Événement supprimé');await refreshAdminData()}catch(e){toast(e.message,true)}}
async function adminSetEventStatus(id,status){try{await api(`/api/admin/events/${id}/status`,{method:'POST',body:JSON.stringify({status})});toast(status==='PUBLIE'?'Événement publié':'Événement refusé');refreshAdminData()}catch(e){toast(e.message,true)}}
function readImage(file){return new Promise((resolve,reject)=>{if(!file)return resolve('');if(file.size>1500000)return reject(new Error('Affiche trop lourde. Maximum 1,5 Mo.'));const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error('Impossible de lire l’affiche.'));r.readAsDataURL(file);});}
async function handleCreateEvent(e){e.preventDefault();try{const imageUrl=await readImage($('form-event-image')?.files?.[0]);await api('/api/admin/events',{method:'POST',body:JSON.stringify({title:$('form-event-title').value,category:$('form-event-category').value,price:Number($('form-event-price').value),date:$('form-event-date').value,capacity:Number($('form-event-capacity').value),imageUrl})});closeModal('create-event-modal');e.target.reset();toast('Événement publié avec son affiche');refreshAdminData()}catch(err){toast(err.message,true)}}
async function simulateScan(){const code=$('scanner-input').value.trim().toUpperCase(),res=$('scan-result');if(!code)return;try{const d=await api('/api/admin/tickets/scan',{method:'POST',body:JSON.stringify({code})});res.className='p-6 rounded-2xl bg-emerald-100 text-emerald-800';$('scan-icon').innerHTML='<i class="fa-solid fa-circle-check"></i>';$('scan-title').innerText='ENTRÉE AUTORISÉE';$('scan-details').innerText=d.ticket?.customer_name||'Billet valide';}catch(err){res.className='p-6 rounded-2xl bg-rose-100 text-rose-800';$('scan-icon').innerHTML='<i class="fa-solid fa-circle-xmark"></i>';$('scan-title').innerText='BILLET NON VALIDE';$('scan-details').innerText=err.message;}res.classList.remove('hidden')}
async function logoutAdmin(){await api('/api/admin/logout',{method:'POST'});location.reload()}
window.switchTab=switchTab;window.openModal=openModal;window.closeModal=closeModal;window.filterAdminData=filterAdminData;window.adminApproveOrg=adminApproveOrg;window.adminRejectOrg=adminRejectOrg;window.adminDeleteOrg=adminDeleteOrg;window.adminSetEventStatus=adminSetEventStatus;window.handleCreateEvent=handleCreateEvent;window.simulateScan=simulateScan;window.logoutAdmin=logoutAdmin;window.adminSetPayoutStatus=adminSetPayoutStatus;window.createAdminWithdrawal=createAdminWithdrawal;window.adminSetWithdrawalStatus=adminSetWithdrawalStatus;window.downloadPayoutPDF=downloadPayoutPDF;
window.addEventListener('DOMContentLoaded',()=>{refreshAdminData();});

window.adminDeleteEvent=adminDeleteEvent;window.adminDeletePayout=adminDeletePayout;

window.adminDeleteWithdrawal=adminDeleteWithdrawal;

function showAdminPlaceholder(label){toast(label+' sera disponible dans une prochaine version.');}
let dashboardRevenueChart=null,dashboardCategoryChart=null;
function renderDashboardCharts(){if(!window.Chart)return;const labels=[],values=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);labels.push(d.toLocaleDateString('fr-FR',{day:'2-digit',month:'2-digit'}));values.push(0);}const rc=$('revenueChart');if(rc){if(dashboardRevenueChart)dashboardRevenueChart.destroy();dashboardRevenueChart=new Chart(rc,{type:'line',data:{labels,datasets:[{label:'Billets vendus',data:values,borderColor:'#ff8a00',pointBackgroundColor:'#ff8a00',pointRadius:3,tension:.35}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:'#b6c6dc',font:{size:9}}}},scales:{x:{ticks:{color:'#7189aa',font:{size:8}},grid:{display:false}},y:{beginAtZero:true,ticks:{color:'#7189aa',font:{size:8}},grid:{color:'#213654'}}}}});}const cc=$('categoryChart');if(cc){const c={Standard:0,VIP:0,VVIP:0,Autre:0};data.payments.forEach(t=>{const k=t.ticket_type||t.type||'Autre';if(c[k]!==undefined)c[k]++;else c.Autre++;});['standard','vip','vvip','other'].forEach((k,i)=>{if($('count-'+k))$('count-'+k).innerText=Object.values(c)[i]||0});if(dashboardCategoryChart)dashboardCategoryChart.destroy();dashboardCategoryChart=new Chart(cc,{type:'doughnut',data:{labels:Object.keys(c),datasets:[{data:Object.values(c),backgroundColor:['#d9e7f6','#c7dcf2','#b3cfe9','#9bbbd8'],borderWidth:0}]},options:{cutout:'67%',plugins:{legend:{display:false}}}});}}
window.showAdminPlaceholder=showAdminPlaceholder;

let adminChatSelected=null,adminAutoRefreshTimer=null;
async function loadAdminChat(){try{const d=await api('/api/chat/conversations');const el=$('admin-chat-list');if(!el)return;el.innerHTML=(d.conversations||[]).map(c=>`<button onclick="openAdminChat(${c.id})" class="w-full text-left p-3 hover:bg-[#102341] transition"><div class="flex justify-between gap-2"><b class="text-xs text-white">${esc((c.prenom||'')+' '+(c.nom||''))}</b>${c.unread?`<span class="bg-[#ff8a00] text-white rounded-full px-2 py-0.5 text-[9px]">${c.unread}</span>`:''}</div><div class="text-[9px] text-[#7892b5] truncate mt-1">${esc(c.last_message||'Aucun message')}</div></button>`).join('')||'<div class="p-5 text-xs text-[#7892b5]">Aucune conversation.</div>';if(adminChatSelected)await openAdminChat(adminChatSelected);}catch(e){toast(e.message,true)}}
async function openAdminChat(id){adminChatSelected=id;try{const d=await api(`/api/chat/messages/${id}`);$('admin-chat-header').innerHTML=`${esc((d.organizer.prenom||'')+' '+(d.organizer.nom||''))}<span class="block text-[9px] text-[#7892b5] font-normal mt-1">${esc(d.organizer.email||'')}</span>`;const el=$('admin-chat-messages');el.innerHTML=(d.messages||[]).map(m=>`<div class="flex ${m.sender_role==='ADMIN'?'justify-end':'justify-start'}"><div class="max-w-[75%] rounded-2xl px-4 py-2 ${m.sender_role==='ADMIN'?'bg-[#ff8a00] text-white':'bg-[#0e203e] text-white border border-[#2b4364]'}"><div class="text-xs whitespace-pre-wrap break-words">${esc(m.message)}</div><div class="text-[8px] opacity-70 mt-1">${new Date(m.created_at).toLocaleString('fr-FR')}</div></div></div>`).join('')||'<div class="text-center text-xs text-[#7892b5] mt-20">Aucun message.</div>';el.scrollTop=el.scrollHeight;loadAdminChatListOnly();}catch(e){toast(e.message,true)}}
async function loadAdminChatListOnly(){try{const d=await api('/api/chat/conversations');const el=$('admin-chat-list');if(!el)return;el.innerHTML=(d.conversations||[]).map(c=>`<button onclick="openAdminChat(${c.id})" class="w-full text-left p-3 hover:bg-[#102341] transition"><div class="flex justify-between gap-2"><b class="text-xs text-white">${esc((c.prenom||'')+' '+(c.nom||''))}</b>${c.unread?`<span class="bg-[#ff8a00] text-white rounded-full px-2 py-0.5 text-[9px]">${c.unread}</span>`:''}</div><div class="text-[9px] text-[#7892b5] truncate mt-1">${esc(c.last_message||'Aucun message')}</div></button>`).join('')||'<div class="p-5 text-xs text-[#7892b5]">Aucune conversation.</div>';}catch{}}
async function sendAdminChat(e){e.preventDefault();if(!adminChatSelected)return toast('Sélectionnez un organisateur.',true);const input=$('admin-chat-input'),message=input.value.trim();if(!message)return;try{await api(`/api/chat/messages/${adminChatSelected}`,{method:'POST',body:JSON.stringify({message})});input.value='';await openAdminChat(adminChatSelected);}catch(err){toast(err.message,true)}}
async function loadAdminExtra(t){try{if(t==='cagnottes'){loadAdminCagnottes();}else if(t==='tickets'){const d=await api('/api/admin/payments');$('admin-tickets-list').innerHTML=(d.payments||[]).map(x=>`<tr class="border-b border-[#243b5d]"><td class="p-4 font-mono text-xs">${esc(x.code)}</td><td class="p-4">${esc(x.customer_name)}</td><td class="p-4">${esc(x.event_title)}</td><td class="p-4">${esc(x.ticket_type)}</td><td class="p-4 font-bold">${fmt(x.total_amount)} FCFA</td><td class="p-4">${x.used?'<span class="text-red-400 font-bold">Utilisé</span>':'<span class="text-emerald-400 font-bold">Valide</span>'}</td></tr>`).join('')||'<tr><td colspan="6" class="p-6 text-center text-[#7892b5]">Aucun billet.</td></tr>';}else if(t==='users'){const d=await api('/api/admin/payments'),m={};(d.payments||[]).forEach(x=>{const k=(x.customer_email||'').toLowerCase();if(!k)return;if(!m[k])m[k]={name:x.customer_name,email:x.customer_email,count:0,last:x.created_at};m[k].count++;if(new Date(x.created_at)>new Date(m[k].last))m[k].last=x.created_at});$('admin-users-list').innerHTML=Object.values(m).map(x=>`<tr class="border-b border-[#243b5d]"><td class="p-4 font-bold">${esc(x.name)}</td><td class="p-4">${esc(x.email)}</td><td class="p-4">${x.count}</td><td class="p-4 text-[#7892b5]">${new Date(x.last).toLocaleString('fr-FR')}</td></tr>`).join('')||'<tr><td colspan="4" class="p-6 text-center text-[#7892b5]">Aucun utilisateur.</td></tr>';}else if(t==='logs'){const d=await api('/api/admin/logs');$('admin-logs-list').innerHTML=(d.logs||[]).map(x=>`<tr class="border-b border-[#243b5d]"><td class="p-4 text-xs text-[#7892b5]">${new Date(x.created_at).toLocaleString('fr-FR')}</td><td class="p-4 font-bold">${esc(x.action)}</td><td class="p-4">${esc(x.entity_type||'-')}</td><td class="p-4 text-xs">${esc(JSON.stringify(x.metadata||{}))}</td></tr>`).join('')||'<tr><td colspan="4" class="p-6 text-center text-[#7892b5]">Aucun journal.</td></tr>';}}catch(e){toast(e.message,true)}}
async function loadAdminCagnottes(){try{const d=await api('/api/admin/cagnottes');const el=$('admin-cagnottes-list');if(!el)return;el.innerHTML=(d.cagnottes||[]).map(c=>{const imgs=Array.isArray(c.images)?c.images:[];return `<div class="border border-[#263d5e] rounded-2xl p-4"><div class="flex gap-3">${imgs.slice(0,3).map(x=>`<img src="${esc(x)}" class="w-16 h-12 object-cover rounded-lg">`).join('')}<div class="flex-1"><div class="font-black text-white">${esc(c.title)}</div><div class="text-[10px] text-[#7892b5] mt-1">${esc(c.status)} • ${fmt(c.total_amount)} FCFA collectés${c.target_amount?` / objectif ${fmt(c.target_amount)} FCFA`:''}</div></div></div><p class="text-xs text-[#9bb0ca] mt-3 whitespace-pre-wrap">${esc(c.description)}</p><div class="flex flex-wrap gap-2 mt-4">${c.status==='BROUILLON'?`<button onclick="launchCagnotte(${c.id})" class="bg-emerald-600 text-white px-3 py-2 rounded-lg text-xs font-bold">Lancer</button>`:''}${c.status==='PUBLIE'?`<button onclick="stopCagnotte(${c.id})" class="bg-amber-500 text-white px-3 py-2 rounded-lg text-xs font-bold">Terminer</button><button onclick="viewContributions(${c.id})" class="bg-[#213654] text-white px-3 py-2 rounded-lg text-xs font-bold">Contributions</button>`:''}${c.status!=='PUBLIE'?`<button onclick="deleteCagnotte(${c.id})" class="bg-red-500/10 text-red-300 px-3 py-2 rounded-lg text-xs font-bold">Supprimer</button>`:''}</div></div>`}).join('')||'<div class="p-6 text-center text-xs text-[#7892b5]">Aucune cagnotte.</div>';}catch(e){toast(e.message,true)}}
async function readCagImages(){const files=[...($('cag-images')?.files||[])];if(files.length>6)throw new Error('Maximum 6 images.');return Promise.all(files.map(file=>new Promise((resolve,reject)=>{if(file.size>1500000)return reject(new Error(`Image trop lourde : ${file.name}`));const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error('Impossible de lire une image.'));r.readAsDataURL(file)})))}
async function createCagnotte(e){e.preventDefault();try{const images=await readCagImages();await api('/api/admin/cagnottes',{method:'POST',body:JSON.stringify({title:$('cag-title').value,description:$('cag-description').value,targetAmount:Number($('cag-target').value||0),images})});e.target.reset();toast('Cagnotte créée. Vous pouvez maintenant la lancer.');loadAdminCagnottes();}catch(e){toast(e.message,true)}}
async function launchCagnotte(id){if(!confirm('Lancer cette cagnotte ? Elle sera visible immédiatement au public.'))return;try{await api(`/api/admin/cagnottes/${id}/launch`,{method:'POST'});toast('Cagnotte publiée.');loadAdminCagnottes();}catch(e){toast(e.message,true)}}
async function stopCagnotte(id){if(!confirm('Terminer cette cagnotte ?'))return;try{await api(`/api/admin/cagnottes/${id}/stop`,{method:'POST'});toast('Cagnotte terminée.');loadAdminCagnottes();}catch(e){toast(e.message,true)}}
async function deleteCagnotte(id){if(!confirm('Supprimer cette cagnotte ?'))return;try{await api(`/api/admin/cagnottes/${id}`,{method:'DELETE'});toast('Cagnotte supprimée.');loadAdminCagnottes();}catch(e){toast(e.message,true)}}
async function viewContributions(id){try{const d=await api(`/api/admin/cagnottes/${id}/contributions`);const rows=(d.contributions||[]).map(c=>`${c.contributor_name||'Anonyme'} — ${fmt(c.amount)} FCFA — ${c.status}`).join('\n')||'Aucune contribution.';alert(rows);}catch(e){toast(e.message,true)}}
function toggleAdminAutoRefresh(on){localStorage.setItem('ticketora_auto_refresh',on?'1':'0');if(adminAutoRefreshTimer)clearInterval(adminAutoRefreshTimer);if(on)adminAutoRefreshTimer=setInterval(()=>refreshAdminData(),30000);}
function clearAdminPreferences(){localStorage.removeItem('ticketora_auto_refresh');if($('admin-auto-refresh'))$('admin-auto-refresh').checked=true;toggleAdminAutoRefresh(true);toast('Préférences réinitialisées.');}
window.sendAdminChat=sendAdminChat;window.openAdminChat=openAdminChat;window.loadAdminCagnottes=loadAdminCagnottes;window.createCagnotte=createCagnotte;window.launchCagnotte=launchCagnotte;window.stopCagnotte=stopCagnotte;window.deleteCagnotte=deleteCagnotte;window.viewContributions=viewContributions;window.toggleAdminAutoRefresh=toggleAdminAutoRefresh;window.clearAdminPreferences=clearAdminPreferences;

function showAdminNotifications(){loadAdminExtra('logs');switchTab('logs');toast('Notifications : consultez les journaux d’activité.');}
window.showAdminNotifications=showAdminNotifications;
