const API=(window.TICKETORA_API_URL||'').replace(/\/$/,'');
let data={organizers:[],events:[],payments:[],payouts:[],withdrawals:[]};
const $=id=>document.getElementById(id);
async function api(path,o={}){const r=await fetch(`${API}${path}`,{credentials:'include',...o,headers:{'Content-Type':'application/json',...(o.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.message||'Erreur serveur');return d;}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function fmt(n){return Number(n||0).toLocaleString('fr-FR');}
function toast(m,error=false){const c=$('toast-container');if(!c)return;const e=document.createElement('div');e.className=`px-4 py-3 rounded-xl shadow-lg text-sm font-semibold ${error?'bg-rose-600':'bg-navy-900'} text-white`;e.innerText=m;c.appendChild(e);setTimeout(()=>e.remove(),3000);}
function switchTab(t){['overview','events','organizers','payments','scanner'].forEach(x=>{document.getElementById(`tab-${x}`)?.classList.toggle('hidden',x!==t);document.getElementById(`nav-${x}`)?.classList.toggle('active',x===t);});if(t!=='scanner')refreshAdminData();}
function openModal(id){$(id)?.classList.remove('hidden')} function closeModal(id){$(id)?.classList.add('hidden')}
function filterAdminData(){const q=($('global-search-input')?.value||'').toLowerCase();document.querySelectorAll('#admin-events-list tr,#admin-org-list tr').forEach(r=>r.classList.toggle('hidden',!r.innerText.toLowerCase().includes(q)));}
function showAdminLogin(){if($('admin-login-overlay'))return;const d=document.createElement('div');d.id='admin-login-overlay';d.className='fixed inset-0 bg-slate-900/95 backdrop-blur-sm z-[100] flex items-center justify-center p-4';d.innerHTML=`<div class="bg-white w-full max-w-md rounded-2xl p-7 shadow-2xl"><div class="text-center mb-6"><img src="logo.png" class="w-14 h-14 mx-auto rounded-xl object-contain"><h2 class="text-2xl font-black text-navy-900 mt-3">Connexion Admin</h2><p class="text-sm text-slate-500">Accès sécurisé au tableau de bord Ticketora</p></div><form id="admin-login-form" class="space-y-4"><input id="admin-login-email" type="email" required value="ticketora2026@gmail.com" class="w-full p-3 bg-slate-50 border rounded-xl"><input id="admin-login-password" type="password" required placeholder="Mot de passe" class="w-full p-3 bg-slate-50 border rounded-xl"><div id="admin-login-error" class="hidden text-sm text-rose-600 font-semibold"></div><button class="w-full bg-brand-orange hover:bg-brand-orangeDark text-white font-bold py-3 rounded-xl">Se connecter</button></form></div>`;document.body.appendChild(d);$('admin-login-form').onsubmit=loginAdmin;}
async function loginAdmin(e){e.preventDefault();try{await api('/api/admin/login',{method:'POST',body:JSON.stringify({email:$('admin-login-email').value,password:$('admin-login-password').value})});$('admin-login-overlay')?.remove();await refreshAdminData();toast('Connexion réussie');}catch(err){$('admin-login-error').innerText=err.message;$('admin-login-error').classList.remove('hidden');}}
async function ensureAdmin(){try{await api('/api/admin/me');return true}catch{showAdminLogin();return false;}}
function renderOrganizers(){const el=$('admin-org-list');if(!el)return;el.innerHTML=data.organizers.map(o=>`<tr class="border-b text-sm"><td class="p-4 font-bold">${esc(o.nom)} ${esc(o.prenom)}</td><td class="p-4 text-slate-500">${esc(o.email)}<br><span class="text-xs">${esc(o.phone)}</span></td><td class="p-4">${fmt(o.event_count)}</td><td class="p-4">${fmt(o.tickets_sold)}</td><td class="p-4 font-bold">${fmt(o.revenue)} FCFA</td><td class="p-4"><span class="px-2 py-1 rounded text-[10px] font-bold ${o.status==='VALIDE'?'bg-emerald-100 text-emerald-700':o.status==='REFUSE'?'bg-red-100 text-red-700':'bg-amber-100 text-amber-700'}">${esc(o.status)}</span></td><td class="p-4 text-right whitespace-nowrap">${o.status==='EN_ATTENTE'?`<button onclick="adminApproveOrg(${o.id})" class="text-xs bg-emerald-600 text-white px-2 py-1 rounded font-bold">Valider</button><button onclick="adminRejectOrg(${o.id})" class="text-xs bg-red-600 text-white px-2 py-1 rounded font-bold ml-1">Refuser</button>`:''}<button onclick="adminDeleteOrg(${o.id})" class="text-xs bg-slate-100 text-red-600 px-2 py-1 rounded font-bold ml-1">Supprimer</button></td></tr>`).join('')||'<tr><td colspan="7" class="p-6 text-center text-slate-400">Aucun organisateur.</td></tr>';}
function renderEvents(){const el=$('admin-events-list');if(!el)return;el.innerHTML=data.events.map(e=>`<tr class="border-b text-sm"><td class="p-4"><div class="flex items-center gap-3">${e.image_url?`<img src="${esc(e.image_url)}" class="w-12 h-12 rounded-lg object-cover border">`:''}<div><span class="font-bold">${esc(e.title)}</span><br><span class="text-xs text-slate-400">${esc(e.organizer_name||'Ticketora')}</span></div></div></td><td class="p-4">${esc(e.category)}</td><td class="p-4">${fmt(e.price)} FCFA</td><td class="p-4">${fmt(e.capacity)}<br><span class="text-xs text-slate-400">${fmt(e.sold_count)} vendus</span></td><td class="p-4"><span class="px-2 py-1 rounded text-[10px] font-bold ${e.status==='PUBLIE'?'bg-emerald-100 text-emerald-700':e.status==='REFUSE'?'bg-red-100 text-red-700':'bg-amber-100 text-amber-700'}">${esc(e.status)}</span></td><td class="p-4 text-right">${e.status!=='PUBLIE'?`<button onclick="adminSetEventStatus(${e.id},'PUBLIE')" class="text-xs bg-emerald-600 text-white px-2 py-1 rounded font-bold">Valider</button>`:''}${e.status!=='REFUSE'?`<button onclick="adminSetEventStatus(${e.id},'REFUSE')" class="text-xs bg-red-600 text-white px-2 py-1 rounded font-bold ml-1">Refuser</button>`:''}<button onclick="adminDeleteEvent(${e.id})" class="text-xs bg-slate-200 text-red-600 px-2 py-1 rounded font-bold ml-1"><i class="fa-solid fa-trash"></i></button></td></tr>`).join('')||'<tr><td colspan="6" class="p-6 text-center text-slate-400">Aucun événement.</td></tr>';}
function renderPayments(){const el=$('admin-payments-list');if(!el)return;el.innerHTML=data.payments.map(t=>`<tr class="border-b text-sm"><td class="p-4 font-mono font-bold">${esc(t.code)}</td><td class="p-4">${esc(t.customer_name)}<br><span class="text-xs text-slate-400">${esc(t.customer_email)}</span></td><td class="p-4">${esc(t.event_title)}</td><td class="p-4 font-bold">${fmt(t.total_amount)} FCFA</td><td class="p-4 text-emerald-600 font-bold">${fmt(t.admin_commission)} FCFA</td><td class="p-4">${esc(t.created_at||'')}</td></tr>`).join('')||'<tr><td colspan="6" class="p-6 text-center text-slate-400">Aucune transaction.</td></tr>';}
function statusBadge(status){return `<span class="px-2 py-1 rounded text-[10px] font-bold ${status==='PAYE'?'bg-emerald-100 text-emerald-700':status==='REFUSE'?'bg-red-100 text-red-700':status==='VALIDE'?'bg-blue-100 text-blue-700':'bg-amber-100 text-amber-700'}">${esc(status)}</span>`;}
function downloadPayoutPDF(p){if(!window.jspdf?.jsPDF){toast('Le module PDF n’est pas chargé.',true);return;}const {jsPDF}=window.jspdf;const doc=new jsPDF();doc.setFontSize(20);doc.text('TICKETORA',20,20);doc.setFontSize(14);doc.text('Justificatif de retrait',20,32);doc.setFontSize(11);const lines=[`ID : ${p.id}`,`Organisateur : ${p.nom||''} ${p.prenom||''}`,`Email : ${p.email||''}`,`Compte : ${p.account||''}`,`Montant : ${fmt(p.amount)} FCFA`,`Statut : ${p.status}`,`Date de demande : ${p.created_at||''}`,`Date de traitement : ${p.processed_at||'-'}`];lines.forEach((x,i)=>doc.text(x,20,48+i*10));doc.setFontSize(9);doc.text('Document généré depuis l’espace administrateur Ticketora.',20,145);doc.save(`Retrait_Organisateur_${p.id}.pdf`);}
function renderPayouts(){const el=$('admin-payouts-list');if(!el)return;el.innerHTML=data.payouts.map(p=>`<tr class="border-b text-sm"><td class="p-4 font-bold">${esc(p.nom||'')} ${esc(p.prenom||'')}<br><span class="text-xs text-slate-400">${esc(p.email||'')}</span></td><td class="p-4 font-mono">${esc(p.account)}</td><td class="p-4 font-bold">${fmt(p.amount)} FCFA</td><td class="p-4">${statusBadge(p.status)}</td><td class="p-4 text-xs text-slate-500">${esc(p.created_at||'')}</td><td class="p-4 text-right whitespace-nowrap">${p.status==='EN_ATTENTE'?`<button onclick="adminSetPayoutStatus(${p.id},'VALIDE')" class="text-xs bg-emerald-600 text-white px-2 py-1 rounded font-bold">Valider</button><button onclick="adminSetPayoutStatus(${p.id},'REFUSE')" class="text-xs bg-red-600 text-white px-2 py-1 rounded font-bold ml-1">Refuser</button>`:p.status==='VALIDE'?`<button onclick="adminSetPayoutStatus(${p.id},'PAYE')" class="text-xs bg-blue-600 text-white px-2 py-1 rounded font-bold">Marquer payé</button>`:''}${['VALIDE','PAYE'].includes(p.status)?`<button onclick='downloadPayoutPDF(${JSON.stringify(p).replace(/'/g,"&#39;")})' class="text-xs bg-slate-900 text-white px-2 py-1 rounded font-bold ml-1"><i class="fa-solid fa-file-pdf"></i> PDF</button>`:''}${['EN_ATTENTE','REFUSE'].includes(p.status)?`<button onclick="adminDeletePayout(${p.id})" class="text-xs bg-slate-200 text-red-600 px-2 py-1 rounded font-bold ml-1"><i class="fa-solid fa-trash"></i></button>`:''}</td></tr>`).join('')||'<tr><td colspan="6" class="p-6 text-center text-slate-400">Aucune demande de retrait.</td></tr>';}
function renderAdminWithdrawals(wd){const b=$('admin-withdrawal-balance');if(b)b.innerText=fmt(wd?.balance||0);const el=$('admin-withdrawals-list');if(!el)return;el.innerHTML=(data.withdrawals||[]).map(p=>`<tr class="border-b text-sm"><td class="p-4 font-bold">${fmt(p.amount)} FCFA</td><td class="p-4 font-mono">${esc(p.account)}</td><td class="p-4">${statusBadge(p.status)}</td><td class="p-4 text-xs text-slate-500">${esc(p.created_at||'')}</td><td class="p-4 text-right">${p.status==='EN_ATTENTE'?`<button onclick="adminSetWithdrawalStatus(${p.id},'PAYE')" class="text-xs bg-emerald-600 text-white px-2 py-1 rounded font-bold">Marquer payé</button><button onclick="adminSetWithdrawalStatus(${p.id},'REFUSE')" class="text-xs bg-red-600 text-white px-2 py-1 rounded font-bold ml-1">Refuser</button>`:''}${['EN_ATTENTE','REFUSE'].includes(p.status)?`<button onclick="adminDeleteWithdrawal(${p.id})" class="text-xs bg-slate-200 text-red-600 px-2 py-1 rounded font-bold ml-1"><i class="fa-solid fa-trash"></i></button>`:''}</td></tr>`).join('')||'<tr><td colspan="5" class="p-6 text-center text-slate-400">Aucun retrait admin.</td></tr>';}
async function adminDeletePayout(id){if(!confirm('Supprimer cette demande de retrait ?'))return;try{await api(`/api/admin/payouts/${id}`,{method:'DELETE'});toast('Demande supprimée');await refreshAdminData()}catch(e){toast(e.message,true)}}
async function adminSetPayoutStatus(id,status){if(status==='REFUSE'&&!confirm('Refuser cette demande de retrait ?'))return;try{await api(`/api/admin/payouts/${id}/status`,{method:'POST',body:JSON.stringify({status})});toast(status==='VALIDE'?'Retrait validé':status==='PAYE'?'Retrait marqué comme payé':'Retrait refusé');await refreshAdminData();}catch(e){toast(e.message,true);}}
async function createAdminWithdrawal(e){e.preventDefault();const amount=Number($('admin-withdrawal-amount').value),account=$('admin-withdrawal-account').value.trim();if(!amount||!account)return toast('Montant et compte obligatoires.',true);try{await api('/api/admin/withdrawals',{method:'POST',body:JSON.stringify({amount,account})});$('admin-withdrawal-form').reset();toast('Demande de retrait admin créée');await refreshAdminData();}catch(err){toast(err.message,true);}}
async function adminDeleteWithdrawal(id){if(!confirm('Supprimer ce retrait administrateur ?'))return;try{await api(`/api/admin/withdrawals/${id}`,{method:'DELETE'});toast('Retrait supprimé');await refreshAdminData()}catch(e){toast(e.message,true)}}
async function adminSetWithdrawalStatus(id,status){if(status==='REFUSE'&&!confirm('Refuser ce retrait admin ?'))return;try{await api(`/api/admin/withdrawals/${id}/status`,{method:'POST',body:JSON.stringify({status})});toast(status==='PAYE'?'Retrait admin marqué comme payé':'Retrait admin refusé');await refreshAdminData();}catch(e){toast(e.message,true);}}
async function refreshAdminData(){if(!(await ensureAdmin()))return;try{const [o,e,p,ov,po,wd]=await Promise.all([api('/api/admin/organizers'),api('/api/admin/events'),api('/api/admin/payments'),api('/api/admin/overview'),api('/api/admin/payouts'),api('/api/admin/withdrawals')]);data.organizers=o.organizers||[];data.events=e.events||[];data.payments=p.payments||[];data.payouts=po.payouts||[];data.withdrawals=wd.withdrawals||[];const st=ov.stats||{};$('stat-revenue').innerHTML=`${fmt(st.revenue)} FCFA<span class="text-xs text-slate-400 font-normal block mt-1">Volume : ${fmt(st.volume)} FCFA</span>`;$('stat-tickets').innerText=st.tickets||0;$('stat-events').innerText=st.events||0;$('stat-pending-orgs').innerText=st.pendingOrganizers||0;if($('badge-org-pending'))$('badge-org-pending').innerText=`${st.pendingOrganizers||0} Attente`;if($('badge-events-count'))$('badge-events-count').innerText=data.events.length;renderOrganizers();renderEvents();renderPayments();renderPayouts();renderAdminWithdrawals(wd);const a=$('dashboard-recent-sales-list');if(a)a.innerHTML=(ov.sales||[]).slice(0,5).map(t=>`<div class="flex justify-between py-2 border-b border-slate-100 text-xs"><span class="font-bold">${esc(t.customer_name)}</span><span>${fmt(t.total_amount)} FCFA</span></div>`).join('')||'<p class="text-xs text-slate-400">Aucune vente.</p>';const b=$('dashboard-pending-orgs-list');if(b)b.innerHTML=data.organizers.filter(o=>o.status==='EN_ATTENTE').slice(0,5).map(o=>`<div class="flex justify-between py-2 border-b border-slate-100 text-xs"><span>${esc(o.nom)}</span><button onclick="adminApproveOrg(${o.id})" class="text-emerald-600 font-bold">Valider</button></div>`).join('')||'<p class="text-xs text-slate-400">Aucune demande en attente.</p>';}catch(e){console.error(e);toast(e.message,true);}}
async function adminApproveOrg(id){try{await api(`/api/admin/organizers/${id}/approve`,{method:'POST'});toast('Organisateur validé');refreshAdminData()}catch(e){toast(e.message,true)}}
async function adminRejectOrg(id){if(!confirm('Refuser cette demande ?'))return;try{await api(`/api/admin/organizers/${id}/reject`,{method:'POST'});toast('Demande refusée');refreshAdminData()}catch(e){toast(e.message,true)}}
async function adminDeleteOrg(id){if(!confirm('Supprimer cet organisateur ?'))return;try{await api(`/api/admin/organizers/${id}`,{method:'DELETE'});toast('Organisateur supprimé');refreshAdminData()}catch(e){toast(e.message,true)}}
async function adminDeleteEvent(id){if(!confirm('Supprimer définitivement cet événement ?'))return;try{await api(`/api/admin/events/${id}`,{method:'DELETE'});toast('Événement supprimé');await refreshAdminData()}catch(e){toast(e.message,true)}}
async function adminSetEventStatus(id,status){try{await api(`/api/admin/events/${id}/status`,{method:'POST',body:JSON.stringify({status})});toast(status==='PUBLIE'?'Événement publié':'Événement refusé');refreshAdminData()}catch(e){toast(e.message,true)}}
function readImage(file){return new Promise((resolve,reject)=>{if(!file)return resolve('');if(file.size>1500000)return reject(new Error('Affiche trop lourde. Maximum 1,5 Mo.'));const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error('Impossible de lire l’affiche.'));r.readAsDataURL(file);});}
async function handleCreateEvent(e){e.preventDefault();try{const imageUrl=await readImage($('form-event-image')?.files?.[0]);await api('/api/admin/events',{method:'POST',body:JSON.stringify({title:$('form-event-title').value,category:$('form-event-category').value,price:Number($('form-event-price').value),date:$('form-event-date').value,capacity:Number($('form-event-capacity').value),imageUrl})});closeModal('create-event-modal');e.target.reset();toast('Événement publié avec son affiche');refreshAdminData()}catch(err){toast(err.message,true)}}
async function simulateScan(){const code=$('scanner-input').value.trim().toUpperCase(),res=$('scan-result');if(!code)return;try{const d=await api('/api/admin/tickets/scan',{method:'POST',body:JSON.stringify({code})});res.className='p-6 rounded-2xl bg-emerald-100 text-emerald-800';$('scan-icon').innerHTML='<i class="fa-solid fa-circle-check"></i>';$('scan-title').innerText='ENTRÉE AUTORISÉE';$('scan-details').innerText=d.ticket?.customer_name||'Billet valide';}catch(err){res.className='p-6 rounded-2xl bg-rose-100 text-rose-800';$('scan-icon').innerHTML='<i class="fa-solid fa-circle-xmark"></i>';$('scan-title').innerText='BILLET NON VALIDE';$('scan-details').innerText=err.message;}res.classList.remove('hidden')}
async function logoutAdmin(){await api('/api/admin/logout',{method:'POST'});location.reload()}
window.switchTab=switchTab;window.openModal=openModal;window.closeModal=closeModal;window.filterAdminData=filterAdminData;window.adminApproveOrg=adminApproveOrg;window.adminRejectOrg=adminRejectOrg;window.adminDeleteOrg=adminDeleteOrg;window.adminSetEventStatus=adminSetEventStatus;window.handleCreateEvent=handleCreateEvent;window.simulateScan=simulateScan;window.logoutAdmin=logoutAdmin;window.adminSetPayoutStatus=adminSetPayoutStatus;window.createAdminWithdrawal=createAdminWithdrawal;window.adminSetWithdrawalStatus=adminSetWithdrawalStatus;window.downloadPayoutPDF=downloadPayoutPDF;
window.addEventListener('DOMContentLoaded',()=>{refreshAdminData();});

window.adminDeleteEvent=adminDeleteEvent;window.adminDeletePayout=adminDeletePayout;

window.adminDeleteWithdrawal=adminDeleteWithdrawal;
