const API=(window.TICKETORA_API_URL||'').replace(/\/$/,'');
let cachedEvents=[];let activeBuyingEvent=null;let activeBuyingCategory=null;let appliedDiscount=0;let paymentPollTimer=null;
const $=id=>document.getElementById(id);
async function api(path,options={}){const r=await fetch(`${API}${path}`,{credentials:'include',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.message||'Erreur serveur');return d;}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function fmt(n){return Number(n||0).toLocaleString('fr-FR');}
async function fetchPublicEvents(){try{const d=await api('/api/events');cachedEvents=d.events||[];renderPublicEvents();}catch(e){console.error(e);const g=$('client-events-grid');if(g)g.innerHTML='<p class="text-sm text-rose-400">Impossible de charger les événements.</p>';}}
function showSection(id){['client-home','client-events','client-verify'].forEach(x=>$(x)?.classList.add('hidden'));$(id)?.classList.remove('hidden');if(id==='client-events')fetchPublicEvents();}
function renderPublicEvents(){const grid=$('client-events-grid');if(!grid)return;grid.innerHTML=cachedEvents.map(e=>{let cats=Array.isArray(e.ticket_categories)?e.ticket_categories:[];const price=cats.length?Math.min(...cats.map(c=>Number(c.price||0))):Number(e.price||0);return `<div class="bg-slate-800 rounded-2xl border border-slate-700 overflow-hidden flex flex-col justify-between p-5 space-y-4">${e.image_url?`<img src="${esc(e.image_url)}" alt="Affiche ${esc(e.title)}" class="w-full h-48 object-cover rounded-xl border border-slate-700">`:''}<div class="space-y-2"><span class="text-[10px] font-bold uppercase bg-orange-500/10 text-[#F97316] border border-orange-500/20 px-2 py-0.5 rounded-full">${esc(e.category||'Événement')}</span><h3 class="text-xl font-bold text-white">${esc(e.title)}</h3><p class="text-xs text-slate-400"><i class="fa-solid fa-location-dot"></i> ${esc(e.location)} | <i class="fa-solid fa-calendar"></i> ${esc(e.date)}</p><p class="text-xs text-slate-300 line-clamp-2">${esc(e.description||'')}</p></div><div class="flex items-center justify-between border-t border-slate-700 pt-4"><span class="text-lg font-black text-emerald-400">À partir de ${fmt(price)} FCFA</span><button onclick="openBuyModal(${Number(e.id)})" class="bg-[#F97316] hover:bg-orange-600 text-white font-bold px-4 py-2 rounded-xl text-xs transition">Acheter</button></div></div>`}).join('')||'<p class="text-slate-400 text-sm">Aucun événement publié.</p>';}
function filterEvents(){const s=($('search-event')?.value||'').toLowerCase(),cat=$('filter-category')?.value||'ALL';document.querySelectorAll('#client-events-grid > div').forEach(card=>{const text=card.innerText.toLowerCase();const cm=cat==='ALL'||text.includes(cat.toLowerCase());card.classList.toggle('hidden',!(cm&&text.includes(s)));});}
function openBuyModal(eventId){activeBuyingEvent=cachedEvents.find(e=>Number(e.id)===Number(eventId));if(!activeBuyingEvent)return;let cats=Array.isArray(activeBuyingEvent.ticket_categories)?activeBuyingEvent.ticket_categories:[];if(!cats.length)cats=[{name:'Standard',price:Number(activeBuyingEvent.price||0),total_stock:Number(activeBuyingEvent.capacity||0)}];activeBuyingCategory=cats[0];const sel=$('buy-ticket-type');sel.innerHTML=cats.map((c,i)=>`<option value="${esc(c.name)}">${esc(c.name)} — ${fmt(c.price)} FCFA</option>`).join('');sel.onchange=()=>{activeBuyingCategory=cats.find(c=>c.name===sel.value)||cats[0];updateBuyPrice();};appliedDiscount=0;updateBuyPrice();$('modal-event-title').innerText=activeBuyingEvent.title;$('buy-step-1').classList.remove('hidden');$('buy-step-2').classList.add('hidden');$('modal-buy-ticket').classList.remove('hidden');}
function updateBuyPrice(){if(!activeBuyingCategory)return;const base=Number(activeBuyingCategory.price||0);const total=Math.round(base*(1-appliedDiscount));$('modal-event-price').innerText=`Prix : ${fmt(total)} FCFA${appliedDiscount?' (promo appliquée)':''}`;}
function closeBuyModal(){if(paymentPollTimer)clearInterval(paymentPollTimer);$('modal-buy-ticket').classList.add('hidden');}
function applyPromoCode(){const p=($('buy-promo')?.value||'').trim().toUpperCase();if(p==='PROMO10'){appliedDiscount=.10;alert('Code Promo de 10% appliqué !');}else{appliedDiscount=0;alert(p?'Code promo invalide.':'Aucun code promo saisi.');}updateBuyPrice();}
async function processPayment(){if(!activeBuyingEvent||!activeBuyingCategory)return;const name=$('buy-name').value.trim(),email=$('buy-email').value.trim(),promo=$('buy-promo').value.trim().toUpperCase();if(!name||!email)return alert('Veuillez remplir tous les champs.');try{const d=await api('/api/payments/create',{method:'POST',body:JSON.stringify({eventId:activeBuyingEvent.id,name,email,ticketType:activeBuyingCategory.name,promo})});window.location.href=d.payment_url;}catch(e){alert(e.message);}}
function setupPaymentReturn(){const q=new URLSearchParams(location.search);const token=q.get('token');const mode=q.get('payment');if(!token||mode!=='return')return;showSection('client-events');$('modal-buy-ticket').classList.remove('hidden');$('buy-step-1').classList.add('hidden');$('buy-step-2').classList.add('hidden');const box=$('buy-step-2');box.classList.remove('hidden');box.innerHTML='<div class="bg-slate-900/50 rounded-2xl p-8 text-center space-y-4"><div class="text-4xl">⏳</div><h3 class="text-xl font-bold text-white">Confirmation du paiement…</h3><p class="text-sm text-slate-400">Ticketora vérifie la confirmation réelle du paiement.</p></div>';let tries=0;paymentPollTimer=setInterval(async()=>{tries++;try{const d=await api(`/api/payments/${encodeURIComponent(token)}/status`);if(d.paid&&d.ticket){clearInterval(paymentPollTimer);renderTicket(d.ticket);return;}if(['cancelled','failed'].includes(d.status)||tries>=20){clearInterval(paymentPollTimer);box.innerHTML='<div class="bg-rose-500/10 border border-rose-500/20 rounded-2xl p-6 text-center"><p class="text-rose-400 font-bold">Paiement non confirmé.</p><button onclick="closeBuyModal()" class="mt-4 bg-slate-700 text-white px-4 py-2 rounded-xl">Fermer</button></div>';}}catch(e){if(tries>=20){clearInterval(paymentPollTimer);box.innerHTML='<div class="p-6 text-center text-rose-400">Vérification impossible pour le moment. Réessayez dans quelques instants.</div>';}}},4000);}
function renderTicket(t){$('buy-step-2').innerHTML=`<div class="space-y-4 text-center"><div id="ticket-pdf-area" class="relative overflow-hidden mx-auto bg-white" style="width:1200px;height:560px;max-width:100%;aspect-ratio:1200/560;"><img src="ticket-template.jpeg" class="absolute inset-0 w-full h-full object-cover"><div class="absolute left-[17%] top-[29%] w-[50%] text-left"><div id="ticket-event-display" class="font-black text-[26px] text-[#0F172A] leading-tight">${esc(t.event_title)}</div></div><div class="absolute left-[17%] top-[43%] w-[50%] text-left font-bold text-[18px] text-[#0F172A]">${esc(t.event_date)}</div><div class="absolute left-[17%] top-[54%] w-[50%] text-left font-bold text-[18px] text-[#0F172A]">${esc(t.event_location)}</div><div class="absolute left-[17%] top-[65%] w-[50%] text-left font-bold text-[18px] text-[#0F172A]">${esc(t.ticket_type)}</div><div class="absolute left-[17%] top-[76%] w-[50%] text-left font-bold text-[18px] text-[#0F172A]">${esc(t.customer_name)}</div><div class="absolute right-[5.5%] top-[28%] w-[16%] flex flex-col items-center gap-2"><div id="qrcode" class="bg-white p-2 rounded-lg"></div><div id="ticket-code-display" class="font-mono text-[13px] font-black text-[#0F172A] bg-white/90 px-2 py-1 rounded">${esc(t.code)}</div></div></div><p class="text-xs text-slate-400">Paiement confirmé. Votre billet est unique.</p><button onclick="downloadPDF()" class="w-full bg-[#F97316] hover:bg-orange-600 text-white font-bold py-3 rounded-xl transition flex items-center justify-center gap-2"><i class="fa-solid fa-download"></i> Télécharger mon billet (PDF)</button></div>`;new QRCode($('qrcode'),{text:t.code,width:120,height:120});}
function downloadPDF(){const el=$('ticket-pdf-area');if(!el)return;html2pdf().set({margin:0,filename:`Billet_${$('ticket-code-display')?.innerText||'Ticketora'}.pdf`,image:{type:'jpeg',quality:.98},html2canvas:{scale:2,useCORS:true,backgroundColor:'#fff'},jsPDF:{unit:'px',format:[1200,560],orientation:'landscape'}}).from(el).save();}
async function verifyTicketPublic(){const code=($('public-scan-input')?.value||'').trim().toUpperCase(),r=$('public-scan-result');if(!code){r.innerHTML='<div class="p-3 bg-amber-500/10 text-amber-400 rounded-xl text-xs font-bold">Saisissez un code.</div>';return;}try{const d=await api(`/api/tickets/verify/${encodeURIComponent(code)}`);r.innerHTML=`<div class="p-4 rounded-xl ${d.status==='VALID'?'bg-emerald-500/10 text-emerald-400':'bg-amber-500/10 text-amber-400'} text-xs font-bold">${esc(d.message)}<br><span class="font-normal">${esc(d.ticket?.event_title||'')}</span></div>`;}catch(e){r.innerHTML='<div class="p-4 bg-red-500/10 text-red-400 rounded-xl text-xs font-bold">BILLET NON VALIDE</div>';}}

// Organisateur
function toggleOrgAuth(mode){$('form-org-login-box').classList.toggle('hidden',mode!=='login');$('form-org-register-box').classList.toggle('hidden',mode!=='register');$('tab-org-login').className=`w-1/2 text-center pb-2 font-bold text-sm ${mode==='login'?'text-[#F97316] border-b-2 border-[#F97316]':'text-slate-400'}`;$('tab-org-register').className=`w-1/2 text-center pb-2 font-bold text-sm ${mode==='register'?'text-[#F97316] border-b-2 border-[#F97316]':'text-slate-400'}`;}
function msg(id,text,ok=false){const e=$(id);e.innerText=text;e.className=`text-xs p-3 rounded-xl text-center font-semibold ${ok?'bg-emerald-500/10 text-emerald-400':'bg-rose-500/10 text-rose-400'}`;e.classList.remove('hidden');}
async function handleOrgLogin(e){e.preventDefault();try{const d=await api('/api/organizers/login',{method:'POST',body:JSON.stringify({email:$('login-org-email').value,password:$('login-org-password').value})});$('org-auth-screen').classList.add('hidden');$('org-dashboard-screen').classList.remove('hidden');$('active-org-name').innerText=d.organizer.nom;await refreshOrgData();}catch(err){msg('org-login-message',err.message);}}
async function handleOrgRegister(e){e.preventDefault();try{await api('/api/organizers/request',{method:'POST',body:JSON.stringify({nom:$('reg-org-name').value,prenom:'',email:$('reg-org-email').value,phone:$('reg-org-phone').value,password:$('reg-org-password').value})});msg('org-register-message','Demande envoyée. Attendez la validation de Ticketora.',true);e.target.reset();}catch(err){msg('org-register-message',err.message);}}
async function checkOrgSession(){try{const d=await api('/api/organizers/me');if(d.success){$('org-auth-screen').classList.add('hidden');$('org-dashboard-screen').classList.remove('hidden');$('active-org-name').innerText=d.organizer.nom;await refreshOrgData();}}catch{}}
function switchOrgSection(sec){['stats','events','payouts','scanner','settings'].forEach(x=>$(`org-sec-${x}`)?.classList.add('hidden'));$(`org-sec-${sec}`)?.classList.remove('hidden');if(sec==='events')loadOrgEvents();if(sec==='stats')refreshOrgData();}
function toggleEventForm(){const box=$('org-event-form-box');box.classList.toggle('hidden');if(!box.classList.contains('hidden')&&!$('ticket-categories-container').children.length)addTicketCategoryRow();}
function addTicketCategoryRow(data={}){const c=$('ticket-categories-container'),id='cat_'+Date.now()+Math.floor(Math.random()*1000);c.insertAdjacentHTML('beforeend',`<div id="${id}" class="flex gap-3 items-center bg-slate-50 p-3 rounded-xl border border-slate-200"><input type="text" placeholder="Nom (ex: VIP)" class="cat-name w-1/3 bg-white border rounded-lg p-2 text-xs" value="${esc(data.name||'')}" required><input type="number" min="0" placeholder="Prix (FCFA)" class="cat-price w-1/4 bg-white border rounded-lg p-2 text-xs" value="${data.price??''}" required><input type="number" min="0" placeholder="Quantité / Stock" class="cat-stock w-1/4 bg-white border rounded-lg p-2 text-xs" value="${data.total_stock??''}" required><button type="button" onclick="document.getElementById('${id}').remove()" class="text-red-500 hover:text-red-700 p-2"><i class="fa-solid fa-trash text-xs"></i></button></div>`);}
function collectCats(){return [...document.querySelectorAll('#ticket-categories-container > div')].map(r=>({name:r.querySelector('.cat-name').value.trim(),price:Number(r.querySelector('.cat-price').value),total_stock:Number(r.querySelector('.cat-stock').value)})).filter(x=>x.name);}
async function saveEvent(e){e.preventDefault();const id=$('event-id').value;const cats=collectCats();if(!cats.length)return alert('Ajoutez au moins une catégorie.');const file=$('event-image')?.files?.[0];let imageUrl='';if(file){if(file.size>1500000)return alert('Affiche trop lourde. Maximum 1,5 Mo.');imageUrl=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error('Impossible de lire l’affiche.'));r.readAsDataURL(file);});}const body={title:$('event-title').value,category:$('event-category').value,date:$('event-date').value,location:$('event-location').value,description:$('event-desc').value,price:cats[0].price,capacity:cats.reduce((s,c)=>s+c.total_stock,0),ticketCategories:cats,imageUrl};try{const d=await api(id?`/api/organizers/events/${id}`:'/api/organizers/events',{method:id?'PUT':'POST',body:JSON.stringify(body)});alert(d.message||'Événement enregistré.');toggleEventForm();await refreshOrgData();}catch(err){alert(err.message);}}
async function loadOrgEvents(){try{const d=await api('/api/organizers/events');const list=$('org-my-events-list');list.innerHTML=(d.events||[]).map(e=>`<tr class="border-b text-sm"><td class="p-4 font-bold">${esc(e.title)}</td><td class="p-4 text-slate-500">${esc(e.date)}</td><td class="p-4 font-bold">${fmt(e.price)} FCFA</td><td class="p-4"><span class="px-2 py-1 rounded text-[10px] font-bold ${e.status==='PUBLIE'?'bg-emerald-100 text-emerald-700':e.status==='REFUSE'?'bg-red-100 text-red-700':'bg-amber-100 text-amber-700'}">${esc(e.status)}</span></td><td class="p-4 text-xs text-slate-500">${fmt(e.sold_count)} vendu(s)</td><td class="p-4 text-right"><button onclick="deleteOrgEvent(${e.id})" class="text-xs bg-red-50 text-red-600 px-3 py-1.5 rounded-lg font-bold"><i class="fa-solid fa-trash"></i> Supprimer</button></td></tr>`).join('')||'<tr><td colspan="6" class="p-6 text-center text-slate-400">Aucun événement.</td></tr>';}catch(err){console.error(err);}}
async function renderOrgSalesChart(events=[]){const canvas=$('org-sales-chart');if(!canvas||!window.Chart)return;if(window.ticketoraOrgChart)window.ticketoraOrgChart.destroy();window.ticketoraOrgChart=new Chart(canvas,{type:'bar',data:{labels:events.slice(0,8).map(e=>e.title),datasets:[{label:'Tickets vendus',data:events.slice(0,8).map(e=>Number(e.sold_count||0))}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,ticks:{precision:0}}}}});}
async function refreshOrgData(){try{const d=await api('/api/organizers/stats');const tickets=d.tickets||[],events=d.events||[],payouts=d.payouts||[];const net=Number(d.netRevenue||0);const used=tickets.filter(t=>t.used).length;const pending=payouts.filter(p=>p.status==='EN_ATTENTE').reduce((a,p)=>a+Number(p.amount||0),0);$('org-stat-revenue').innerText=fmt(Math.max(0,net-payouts.filter(p=>['EN_ATTENTE','VALIDE','PAYE'].includes(p.status)).reduce((a,p)=>a+Number(p.amount||0),0)))+' FCFA';$('org-stat-tickets').innerText=tickets.length;$('org-stat-events').innerText=events.length;if($('org-stat-used'))$('org-stat-used').innerText=used;if($('org-stat-pending-payout'))$('org-stat-pending-payout').innerText=fmt(pending)+' FCFA';renderOrgPayouts(payouts);renderOrgSalesChart(events);loadOrgEvents();}catch(err){console.error(err);}}
function downloadOrgPayoutPDF(p){if(!window.jspdf?.jsPDF){alert('Le module PDF n’est pas chargé.');return;}const {jsPDF}=window.jspdf;const doc=new jsPDF();doc.setFontSize(20);doc.text('TICKETORA',20,20);doc.setFontSize(14);doc.text('Justificatif de retrait',20,32);doc.setFontSize(11);[`ID : ${p.id}`,`Montant : ${fmt(p.amount)} FCFA`,`Compte : ${p.account||''}`,`Statut : ${p.status}`,`Date de demande : ${p.created_at||''}`,`Date de traitement : ${p.processed_at||'-'}`].forEach((x,i)=>doc.text(x,20,48+i*10));doc.save(`Mon_Retrait_${p.id}.pdf`);}
function renderOrgPayouts(payouts=[]){const el=$('org-payouts-list');if(!el)return;el.innerHTML=payouts.map(p=>`<tr class="border-b text-sm"><td class="p-3 font-bold">${fmt(p.amount)} FCFA</td><td class="p-3">${esc(p.account)}</td><td class="p-3"><span class="px-2 py-1 rounded text-[10px] font-bold ${p.status==='PAYE'?'bg-emerald-100 text-emerald-700':p.status==='REFUSE'?'bg-red-100 text-red-700':p.status==='VALIDE'?'bg-blue-100 text-blue-700':'bg-amber-100 text-amber-700'}">${esc(p.status)}</span></td><td class="p-3 text-xs text-slate-500">${esc(p.created_at||'')}</td><td class="p-3 text-right">${['VALIDE','PAYE'].includes(p.status)?`<button onclick='downloadOrgPayoutPDF(${JSON.stringify(p).replace(/'/g,"&#39;")})' class="text-xs bg-slate-900 text-white px-2 py-1 rounded font-bold"><i class="fa-solid fa-file-pdf"></i> PDF</button>`:''}${['EN_ATTENTE','REFUSE'].includes(p.status)?`<button onclick="deleteOrgPayout(${p.id})" class="text-xs bg-slate-200 text-red-600 px-2 py-1 rounded font-bold ml-1"><i class="fa-solid fa-trash"></i></button>`:''}</td></tr>`).join('')||'<tr><td colspan="5" class="p-5 text-center text-slate-400">Aucun retrait.</td></tr>';}

async function deleteOrgEvent(id){if(!confirm('Supprimer définitivement cet événement ?'))return;try{await api(`/api/organizers/events/${id}`,{method:'DELETE'});alert('Événement supprimé.');await refreshOrgData()}catch(e){alert(e.message)}}
async function deleteOrgPayout(id){if(!confirm('Supprimer cette demande de retrait ?'))return;try{await api(`/api/payouts/${id}`,{method:'DELETE'});alert('Demande supprimée.');await refreshOrgData()}catch(e){alert(e.message)}}
async function requestPayout(){const amount=Number($('payout-amount').value),account=$('payout-account').value.trim();if(!amount||!account)return alert('Veuillez remplir tous les champs.');try{await api('/api/payouts',{method:'POST',body:JSON.stringify({amount,account})});alert('Demande de retrait envoyée.');$('payout-amount').value='';$('payout-account').value='';}catch(err){alert(err.message);}}
async function scanTicketOrg(){const code=$('org-scan-input').value.trim().toUpperCase(),r=$('org-scan-result');if(!code)return;r.innerHTML='<div class="p-3 bg-slate-100 rounded-xl text-xs">Vérification…</div>';try{const d=await api('/api/tickets/scan',{method:'POST',body:JSON.stringify({code})});r.innerHTML=`<div class="p-4 bg-emerald-100 text-emerald-700 rounded-xl text-xs font-bold">ENTRÉE AUTORISÉE ✅<br><span class="font-normal">${esc(d.ticket?.customer_name||'')}</span></div>`;}catch(err){r.innerHTML=`<div class="p-4 bg-rose-100 text-rose-700 rounded-xl text-xs font-bold">BILLET NON VALIDE ❌<br><span class="font-normal">${esc(err.message)}</span></div>`;}}
async function updateOrgPassword(e){e.preventDefault();try{const d=await api('/api/organizers/password',{method:'POST',body:JSON.stringify({oldPassword:$('pwd-old').value,newPassword:$('pwd-new').value})});msg('pwd-msg',d.message,true);e.target.reset();}catch(err){msg('pwd-msg',err.message);}}
async function logoutOrg(){await api('/api/organizers/logout',{method:'POST'});location.reload();}

window.addEventListener('DOMContentLoaded',()=>{showSection('client-home');fetchPublicEvents();setupPaymentReturn();checkOrgSession();});

window.showSection = showSection;

window.filterEvents = filterEvents;

window.closeBuyModal = closeBuyModal;

window.applyPromoCode = applyPromoCode;

window.downloadPDF = downloadPDF;

window.toggleOrgAuth = toggleOrgAuth;

window.switchOrgSection = switchOrgSection;

window.toggleEventForm = toggleEventForm;

window.addTicketCategoryRow = addTicketCategoryRow;
window.handleOrgLogin = handleOrgLogin;
window.handleOrgRegister = handleOrgRegister;
window.saveEvent = saveEvent;
window.requestPayout = requestPayout;
window.downloadOrgPayoutPDF = downloadOrgPayoutPDF;
window.scanTicketOrg = scanTicketOrg;
window.updateOrgPassword = updateOrgPassword;
window.logoutOrg = logoutOrg;
window.openBuyModal = openBuyModal;
window.processPayment = processPayment;
window.verifyTicketPublic = verifyTicketPublic;

window.deleteOrgEvent=deleteOrgEvent;window.deleteOrgPayout=deleteOrgPayout;
