const API=(window.TICKETORA_API_URL||'').replace(/\/$/,'');
let cachedEvents=[];let activeBuyingEvent=null;let activeBuyingCategory=null;let appliedDiscount=0;let appliedPromo=null;let paymentPollTimer=null;
const $=id=>document.getElementById(id);
async function api(path,options={}){const r=await fetch(`${API}${path}`,{credentials:'include',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.message||'Erreur serveur');return d;}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function fmt(n){return Number(n||0).toLocaleString('fr-FR');}
async function fetchPublicEvents(){try{const d=await api('/api/events');cachedEvents=d.events||[];renderPublicEvents();}catch(e){console.error(e);const g=$('client-events-grid');if(g)g.innerHTML='<p class="text-sm text-rose-400">Impossible de charger les événements.</p>';}}
function showSection(id){['client-home','client-events','client-verify'].forEach(x=>$(x)?.classList.add('hidden'));$(id)?.classList.remove('hidden');if(id==='client-events'){fetchPublicEvents();}if(id==='client-home'){renderPublicEvents();}}
function renderPublicEvents(){
 const grid=document.getElementById('all-events-grid')||document.getElementById('client-events-grid');
 const upcoming=document.getElementById('upcoming-events-grid');
 const empty=document.getElementById('upcoming-events-empty');
 if(!grid&&!upcoming)return;
 const card=e=>{let cats=Array.isArray(e.ticket_categories)?e.ticket_categories:[];const price=cats.length?Math.min(...cats.map(c=>Number(c.price||0))):Number(e.price||0);return `<article class="event-card-public bg-white rounded-2xl border border-slate-200 overflow-hidden flex flex-col shadow-sm">${e.image_url?`<img src="${esc(e.image_url)}" alt="Affiche ${esc(e.title)}" class="w-full h-52 object-cover">`:`<div class="w-full h-52 bg-gradient-to-br from-[#071a3b] to-[#102d5e] flex items-center justify-center"><img src="logo.png" alt="Ticketora" class="w-20 h-20 object-contain opacity-80"></div>`}<div class="p-5 flex flex-col flex-1"><div class="flex items-center justify-between gap-3"><span class="text-[10px] font-black uppercase bg-orange-50 text-[#F97316] border border-orange-100 px-2.5 py-1 rounded-full">${esc(e.category||'Événement')}</span><span class="text-xs text-slate-400 font-semibold"><i class="fa-regular fa-calendar mr-1"></i>${esc(e.date||'')}</span></div><h3 class="text-xl font-black text-[#071a3b] mt-3">${esc(e.title)}</h3><p class="text-xs text-slate-500 font-semibold mt-2"><i class="fa-solid fa-location-dot text-[#F97316] mr-1"></i>${esc(e.location||'')}</p><p class="text-sm text-slate-500 line-clamp-2 mt-3 flex-1">${esc(e.description||'')}</p><div class="flex items-center justify-between gap-3 border-t border-slate-100 mt-5 pt-4"><div><p class="text-[10px] uppercase font-black text-slate-400">À partir de</p><p class="text-lg font-black text-[#071a3b]">${fmt(price)} FCFA</p></div><button onclick="openBuyModal(${Number(e.id)})" class="bg-[#F97316] hover:bg-orange-600 text-white font-bold px-4 py-2.5 rounded-xl text-xs transition">Acheter</button></div></div></article>`};
 const cards=(cachedEvents||[]).map(card).join('');
 if(grid)grid.innerHTML=cards||'<p class="text-slate-500 text-sm font-semibold">Aucun événement publié.</p>';
 if(upcoming){const upcomingEvents=(cachedEvents||[]).slice(0,3);upcoming.innerHTML=upcomingEvents.map(card).join('');if(empty)empty.classList.toggle('hidden',upcomingEvents.length>0);}
}

function filterEvents(){const s=($('search-event')?.value||'').toLowerCase(),cat=$('filter-category')?.value||'ALL';document.querySelectorAll('#all-events-grid > article').forEach(card=>{const text=card.innerText.toLowerCase();const cm=cat==='ALL'||text.includes(cat.toLowerCase());card.classList.toggle('hidden',!(cm&&text.includes(s)));});}
function openBuyModal(eventId){activeBuyingEvent=cachedEvents.find(e=>Number(e.id)===Number(eventId));if(!activeBuyingEvent)return;let cats=Array.isArray(activeBuyingEvent.ticket_categories)?activeBuyingEvent.ticket_categories:[];if(!cats.length)cats=[{name:'Standard',price:Number(activeBuyingEvent.price||0),total_stock:Number(activeBuyingEvent.capacity||0)}];activeBuyingCategory=cats[0];const sel=$('buy-ticket-type');sel.innerHTML=cats.map((c,i)=>`<option value="${esc(c.name)}">${esc(c.name)} — ${fmt(c.price)} FCFA</option>`).join('');sel.onchange=()=>{activeBuyingCategory=cats.find(c=>c.name===sel.value)||cats[0];appliedDiscount=0;appliedPromo=null;$('buy-promo').value='';if($('buy-promo-message'))$('buy-promo-message').innerText='';updateBuyPrice();};appliedDiscount=0;appliedPromo=null;$('buy-promo').value='';if($('buy-promo-message'))$('buy-promo-message').innerText='';updateBuyPrice();$('modal-event-title').innerText=activeBuyingEvent.title;$('buy-step-1').classList.remove('hidden');$('buy-step-2').classList.add('hidden');$('modal-buy-ticket').classList.remove('hidden');}
function updateBuyPrice(){if(!activeBuyingCategory)return;const base=Number(activeBuyingCategory.price||0);const discount=appliedPromo?Number(appliedPromo.discount||0):Math.round(base*appliedDiscount);const total=base-discount;$('modal-event-price').innerHTML=`Prix initial : <b>${fmt(base)} FCFA</b>${discount?`<br><span class=\"text-emerald-400\">Réduction : -${fmt(discount)} FCFA</span>`:''}<br><span class=\"text-white font-black text-sm\">Total : ${fmt(total)} FCFA</span>`;}
function closeBuyModal(){if(paymentPollTimer)clearInterval(paymentPollTimer);$('modal-buy-ticket').classList.add('hidden');}
async function applyPromoCode(){const p=($('buy-promo')?.value||'').trim().toUpperCase(),email=($('buy-email')?.value||'').trim().toLowerCase();if(!p)return alert('Entrez un code promo.');if(!email)return alert('Entrez d’abord votre email pour vérifier les limites d’utilisation.');if(!activeBuyingEvent||!activeBuyingCategory)return;try{const d=await api('/api/promos/validate',{method:'POST',body:JSON.stringify({eventId:activeBuyingEvent.id,ticketType:activeBuyingCategory.name,email,code:p,baseAmount:Number(activeBuyingCategory.price||0)})});appliedPromo=d;appliedDiscount=0;updateBuyPrice();const box=$('buy-promo-message');if(box){box.className='text-xs mt-2 text-emerald-400 font-bold';box.innerText=`✓ ${d.code} appliqué : -${fmt(d.discount)} FCFA`;} }catch(e){appliedPromo=null;appliedDiscount=0;updateBuyPrice();const box=$('buy-promo-message');if(box){box.className='text-xs mt-2 text-rose-400 font-bold';box.innerText=e.message;}else alert(e.message);}}
async function processPayment(){if(!activeBuyingEvent||!activeBuyingCategory)return;const name=$('buy-name').value.trim(),email=$('buy-email').value.trim(),promo=$('buy-promo').value.trim().toUpperCase();if(!name||!email)return alert('Veuillez remplir tous les champs.');try{const d=await api('/api/payments/create',{method:'POST',body:JSON.stringify({eventId:activeBuyingEvent.id,name,email,ticketType:activeBuyingCategory.name,promo})});window.location.href=d.payment_url;}catch(e){alert(e.message);}}
function setupPaymentReturn(){const q=new URLSearchParams(location.search);const token=q.get('token');const mode=q.get('payment');if(!token||mode!=='return')return;showSection('client-events');$('modal-buy-ticket').classList.remove('hidden');$('buy-step-1').classList.add('hidden');$('buy-step-2').classList.add('hidden');const box=$('buy-step-2');box.classList.remove('hidden');box.innerHTML='<div class="bg-slate-900/50 rounded-2xl p-8 text-center space-y-4"><div class="text-4xl">⏳</div><h3 class="text-xl font-bold text-white">Confirmation du paiement…</h3><p class="text-sm text-slate-400">Ticketora vérifie la confirmation réelle du paiement.</p></div>';let tries=0;paymentPollTimer=setInterval(async()=>{tries++;try{const d=await api(`/api/payments/${encodeURIComponent(token)}/status`);if(d.paid&&d.ticket){clearInterval(paymentPollTimer);renderTicket(d.ticket);return;}if(['cancelled','failed'].includes(d.status)||tries>=20){clearInterval(paymentPollTimer);box.innerHTML='<div class="bg-rose-500/10 border border-rose-500/20 rounded-2xl p-6 text-center"><p class="text-rose-400 font-bold">Paiement non confirmé.</p><button onclick="closeBuyModal()" class="mt-4 bg-slate-700 text-white px-4 py-2 rounded-xl">Fermer</button></div>';}}catch(e){if(tries>=20){clearInterval(paymentPollTimer);box.innerHTML='<div class="p-6 text-center text-rose-400">Vérification impossible pour le moment. Réessayez dans quelques instants.</div>';}}},4000);}
function renderTicket(t){$('buy-step-2').innerHTML=`<div class="space-y-4 text-center"><div id="ticket-pdf-area" class="relative overflow-hidden mx-auto bg-white" style="width:1200px;height:560px;max-width:100%;aspect-ratio:1200/560;"><img src="ticket-template.jpeg" class="absolute inset-0 w-full h-full object-cover"><div class="absolute left-[17%] top-[29%] w-[50%] text-left"><div id="ticket-event-display" class="font-black text-[26px] text-[#0F172A] leading-tight">${esc(t.event_title)}</div></div><div class="absolute left-[17%] top-[43%] w-[50%] text-left font-bold text-[18px] text-[#0F172A]">${esc(t.event_date)}</div><div class="absolute left-[17%] top-[54%] w-[50%] text-left font-bold text-[18px] text-[#0F172A]">${esc(t.event_location)}</div><div class="absolute left-[17%] top-[65%] w-[50%] text-left font-bold text-[18px] text-[#0F172A]">${esc(t.ticket_type)}</div><div class="absolute left-[17%] top-[76%] w-[50%] text-left font-bold text-[18px] text-[#0F172A]">${esc(t.customer_name)}</div><div class="absolute right-[5.5%] top-[28%] w-[16%] flex flex-col items-center gap-2"><div id="qrcode" class="bg-white p-2 rounded-lg"></div><div id="ticket-code-display" class="font-mono text-[13px] font-black text-[#0F172A] bg-white/90 px-2 py-1 rounded">${esc(t.code)}</div></div></div><p class="text-xs text-slate-400">Paiement confirmé. Votre billet est unique.</p><button onclick="downloadPDF()" class="w-full bg-[#F97316] hover:bg-orange-600 text-white font-bold py-3 rounded-xl transition flex items-center justify-center gap-2"><i class="fa-solid fa-download"></i> Télécharger mon billet (PDF)</button></div>`;new QRCode($('qrcode'),{text:t.code,width:120,height:120});}
function downloadPDF(){const el=$('ticket-pdf-area');if(!el)return;html2pdf().set({margin:0,filename:`Billet_${$('ticket-code-display')?.innerText||'Ticketora'}.pdf`,image:{type:'jpeg',quality:.98},html2canvas:{scale:2,useCORS:true,backgroundColor:'#fff'},jsPDF:{unit:'px',format:[1200,560],orientation:'landscape'}}).from(el).save();}
async function verifyTicketPublic(){const code=($('public-scan-input')?.value||'').trim().toUpperCase(),r=$('public-scan-result');if(!code){r.innerHTML='<div class="p-3 bg-amber-500/10 text-amber-400 rounded-xl text-xs font-bold">Saisissez un code.</div>';return;}try{const d=await api(`/api/tickets/verify/${encodeURIComponent(code)}`);r.innerHTML=`<div class="p-4 rounded-xl ${d.status==='VALID'?'bg-emerald-500/10 text-emerald-400':'bg-amber-500/10 text-amber-400'} text-xs font-bold">${esc(d.message)}<br><span class="font-normal">${esc(d.ticket?.event_title||'')}</span></div>`;}catch(e){r.innerHTML='<div class="p-4 bg-red-500/10 text-red-400 rounded-xl text-xs font-bold">BILLET NON VALIDE</div>';}}

// Organisateur
function toggleOrgAuth(mode){$('form-org-login-box').classList.toggle('hidden',mode!=='login');$('form-org-register-box').classList.toggle('hidden',mode!=='register');$('tab-org-login').className=`w-1/2 text-center pb-2 font-bold text-sm ${mode==='login'?'text-[#F97316] border-b-2 border-[#F97316]':'text-slate-400'}`;$('tab-org-register').className=`w-1/2 text-center pb-2 font-bold text-sm ${mode==='register'?'text-[#F97316] border-b-2 border-[#F97316]':'text-slate-400'}`;}
function msg(id,text,ok=false){const e=$(id);e.innerText=text;e.className=`text-xs p-3 rounded-xl text-center font-semibold ${ok?'bg-emerald-500/10 text-emerald-400':'bg-rose-500/10 text-rose-400'}`;e.classList.remove('hidden');}
async function handleOrgLogin(e){e.preventDefault();try{const d=await api('/api/organizers/login',{method:'POST',body:JSON.stringify({email:$('login-org-email').value,password:$('login-org-password').value})});$('org-auth-screen').classList.add('hidden');$('org-dashboard-screen').classList.remove('hidden');$('active-org-name').innerText=d.organizer.nom;await refreshOrgData();}catch(err){msg('org-login-message',err.message);}}
async function handleOrgRegister(e){e.preventDefault();try{await api('/api/organizers/request',{method:'POST',body:JSON.stringify({nom:$('reg-org-name').value,prenom:'',email:$('reg-org-email').value,phone:$('reg-org-phone').value,password:$('reg-org-password').value})});msg('org-register-message','Demande envoyée. Attendez la validation de Ticketora.',true);e.target.reset();}catch(err){msg('org-register-message',err.message);}}
async function checkOrgSession(){try{const d=await api('/api/organizers/me');if(d.success){$('org-auth-screen').classList.add('hidden');$('org-dashboard-screen').classList.remove('hidden');$('active-org-name').innerText=d.organizer.nom;await refreshOrgData();}}catch{}}
function switchOrgSection(sec){['stats','events','promos','payouts','scanner','agents','settings','chat'].forEach(x=>$(`org-sec-${x}`)?.classList.add('hidden'));$(`org-sec-${sec}`)?.classList.remove('hidden');if(sec==='events')loadOrgEvents();if(sec==='promos'){loadOrgPromos();populatePromoEvents();}if(sec==='stats')refreshOrgData();if(sec==='chat')loadOrgChat();if(sec==='agents')loadScannerAgents();}
function toggleEventForm(){const box=$('org-event-form-box');box.classList.toggle('hidden');if(!box.classList.contains('hidden')&&!$('ticket-categories-container').children.length)addTicketCategoryRow();}
function addTicketCategoryRow(data={}){const c=$('ticket-categories-container'),id='cat_'+Date.now()+Math.floor(Math.random()*1000);c.insertAdjacentHTML('beforeend',`<div id="${id}" class="flex gap-3 items-center bg-slate-50 p-3 rounded-xl border border-slate-200"><input type="text" placeholder="Nom (ex: VIP)" class="cat-name w-1/3 bg-white border rounded-lg p-2 text-xs" value="${esc(data.name||'')}" required><input type="number" min="0" placeholder="Prix (FCFA)" class="cat-price w-1/4 bg-white border rounded-lg p-2 text-xs" value="${data.price??''}" required><input type="number" min="0" placeholder="Quantité / Stock" class="cat-stock w-1/4 bg-white border rounded-lg p-2 text-xs" value="${data.total_stock??''}" required><button type="button" onclick="document.getElementById('${id}').remove()" class="text-red-500 hover:text-red-700 p-2"><i class="fa-solid fa-trash text-xs"></i></button></div>`);}
function collectCats(){return [...document.querySelectorAll('#ticket-categories-container > div')].map(r=>({name:r.querySelector('.cat-name').value.trim(),price:Number(r.querySelector('.cat-price').value),total_stock:Number(r.querySelector('.cat-stock').value)})).filter(x=>x.name);}
async function saveEvent(e){e.preventDefault();const id=$('event-id').value;const cats=collectCats();if(!cats.length)return alert('Ajoutez au moins une catégorie.');const file=$('event-image')?.files?.[0];let imageUrl='';if(file){if(file.size>1500000)return alert('Affiche trop lourde. Maximum 1,5 Mo.');imageUrl=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error('Impossible de lire l’affiche.'));r.readAsDataURL(file);});}const body={title:$('event-title').value,category:$('event-category').value,date:$('event-date').value,location:$('event-location').value,description:$('event-desc').value,price:cats[0].price,capacity:cats.reduce((s,c)=>s+c.total_stock,0),ticketCategories:cats,imageUrl};try{const d=await api(id?`/api/organizers/events/${id}`:'/api/organizers/events',{method:id?'PUT':'POST',body:JSON.stringify(body)});alert(d.message||'Événement enregistré.');toggleEventForm();await refreshOrgData();}catch(err){alert(err.message);}}
async function loadOrgEvents(){try{const d=await api('/api/organizers/events');window.orgEventsCache=d.events||[];const list=$('org-my-events-list');list.innerHTML=(d.events||[]).map(e=>`<tr class="border-b text-sm"><td class="p-4 font-bold">${esc(e.title)}</td><td class="p-4 text-slate-500">${esc(e.date)}</td><td class="p-4 font-bold">${fmt(e.price)} FCFA</td><td class="p-4"><span class="px-2 py-1 rounded text-[10px] font-bold ${e.status==='PUBLIE'?'bg-emerald-100 text-emerald-700':e.status==='REFUSE'?'bg-red-100 text-red-700':'bg-amber-100 text-amber-700'}">${esc(e.status)}</span></td><td class="p-4 text-xs text-slate-500">${fmt(e.sold_count)} vendu(s)</td><td class="p-4 text-right"><button onclick="deleteOrgEvent(${e.id})" class="text-xs bg-red-50 text-red-600 px-3 py-1.5 rounded-lg font-bold"><i class="fa-solid fa-trash"></i> Supprimer</button></td></tr>`).join('')||'<tr><td colspan="6" class="p-6 text-center text-slate-400">Aucun événement.</td></tr>';}catch(err){console.error(err);}}
async function renderOrgSalesChart(events=[]){const canvas=$('org-sales-chart');if(!canvas||!window.Chart)return;if(window.ticketoraOrgChart)window.ticketoraOrgChart.destroy();window.ticketoraOrgChart=new Chart(canvas,{type:'bar',data:{labels:events.slice(0,8).map(e=>e.title),datasets:[{label:'Tickets vendus',data:events.slice(0,8).map(e=>Number(e.sold_count||0))}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,ticks:{precision:0}}}}});}
async function refreshOrgData(){try{const d=await api('/api/organizers/stats');const tickets=d.tickets||[],events=d.events||[],payouts=d.payouts||[];const net=Number(d.netRevenue||0);const used=tickets.filter(t=>t.used).length;const pending=payouts.filter(p=>p.status==='EN_ATTENTE').reduce((a,p)=>a+Number(p.amount||0),0);$('org-stat-revenue').innerText=fmt(Math.max(0,net-payouts.filter(p=>['EN_ATTENTE','VALIDE','PAYE'].includes(p.status)).reduce((a,p)=>a+Number(p.amount||0),0)))+' FCFA';$('org-stat-tickets').innerText=tickets.length;$('org-stat-events').innerText=events.length;if($('org-stat-used'))$('org-stat-used').innerText=used;if($('org-stat-pending-payout'))$('org-stat-pending-payout').innerText=fmt(pending)+' FCFA';renderOrgPayouts(payouts);renderOrgSalesChart(events);loadOrgEvents();}catch(err){console.error(err);}}
function downloadOrgPayoutPDF(p){if(!window.jspdf?.jsPDF){alert('Le module PDF n’est pas chargé.');return;}const {jsPDF}=window.jspdf;const doc=new jsPDF();doc.setFontSize(20);doc.text('TICKETORA',20,20);doc.setFontSize(14);doc.text('Justificatif de retrait',20,32);doc.setFontSize(11);[`ID : ${p.id}`,`Montant : ${fmt(p.amount)} FCFA`,`Compte : ${p.account||''}`,`Statut : ${p.status}`,`Date de demande : ${p.created_at||''}`,`Date de traitement : ${p.processed_at||'-'}`].forEach((x,i)=>doc.text(x,20,48+i*10));doc.save(`Mon_Retrait_${p.id}.pdf`);}
function renderOrgPayouts(payouts=[]){const el=$('org-payouts-list');if(!el)return;el.innerHTML=payouts.map(p=>`<tr class="border-b text-sm"><td class="p-3 font-bold">${fmt(p.amount)} FCFA</td><td class="p-3">${esc(p.account)}</td><td class="p-3"><span class="px-2 py-1 rounded text-[10px] font-bold ${p.status==='PAYE'?'bg-emerald-100 text-emerald-700':p.status==='REFUSE'?'bg-red-100 text-red-700':p.status==='VALIDE'?'bg-blue-100 text-blue-700':'bg-amber-100 text-amber-700'}">${esc(p.status)}</span></td><td class="p-3 text-xs text-slate-500">${esc(p.created_at||'')}</td><td class="p-3 text-right">${['VALIDE','PAYE'].includes(p.status)?`<button onclick='downloadOrgPayoutPDF(${JSON.stringify(p).replace(/'/g,"&#39;")})' class="text-xs bg-slate-900 text-white px-2 py-1 rounded font-bold"><i class="fa-solid fa-file-pdf"></i> PDF</button>`:''}${['EN_ATTENTE','REFUSE'].includes(p.status)?`<button onclick="deleteOrgPayout(${p.id})" class="text-xs bg-slate-200 text-red-600 px-2 py-1 rounded font-bold ml-1"><i class="fa-solid fa-trash"></i></button>`:''}</td></tr>`).join('')||'<tr><td colspan="5" class="p-5 text-center text-slate-400">Aucun retrait.</td></tr>';}

async function deleteOrgEvent(id){if(!confirm('Supprimer définitivement cet événement ?'))return;try{await api(`/api/organizers/events/${id}`,{method:'DELETE'});alert('Événement supprimé.');await refreshOrgData()}catch(e){alert(e.message)}}
async function deleteOrgPayout(id){if(!confirm('Supprimer cette demande de retrait ?'))return;try{await api(`/api/payouts/${id}`,{method:'DELETE'});alert('Demande supprimée.');await refreshOrgData()}catch(e){alert(e.message)}}
async function requestPayout(){const amount=Number($('payout-amount').value),account=$('payout-account').value.trim(),withdrawMode=$('payout-mode')?.value||'';if(!amount||!account||!withdrawMode)return alert('Veuillez remplir tous les champs.');if(amount<200)return alert('Le retrait minimum est de 200 FCFA.');if(!confirm(`Confirmez-vous le retrait de ${fmt(amount)} FCFA vers ${account} via ${$('payout-mode').selectedOptions[0].text} ?\n\nVérifiez bien le numéro : un décaissement Tchin ne peut pas être annulé.`))return;try{const d=await api('/api/payouts',{method:'POST',body:JSON.stringify({amount,account,withdrawMode})});alert('Demande de retrait envoyée à Ticketora. Elle doit être validée par l’administrateur.');$('payout-amount').value='';$('payout-account').value='';await refreshOrgData();}catch(err){alert(err.message);}}
async function scanTicketOrg(){const code=$('org-scan-input').value.trim().toUpperCase(),r=$('org-scan-result');if(!code)return;r.innerHTML='<div class="p-3 bg-slate-100 rounded-xl text-xs">Vérification…</div>';try{const d=await api('/api/tickets/scan',{method:'POST',body:JSON.stringify({code})});r.innerHTML=`<div class="p-4 bg-emerald-100 text-emerald-700 rounded-xl text-xs font-bold">ENTRÉE AUTORISÉE ✅<br><span class="font-normal">${esc(d.ticket?.customer_name||'')}</span></div>`;}catch(err){r.innerHTML=`<div class="p-4 bg-rose-100 text-rose-700 rounded-xl text-xs font-bold">BILLET NON VALIDE ❌<br><span class="font-normal">${esc(err.message)}</span></div>`;}}
async function updateOrgPassword(e){e.preventDefault();try{const d=await api('/api/organizers/password',{method:'POST',body:JSON.stringify({oldPassword:$('pwd-old').value,newPassword:$('pwd-new').value})});msg('pwd-msg',d.message,true);e.target.reset();}catch(err){msg('pwd-msg',err.message);}}
async function logoutOrg(){await api('/api/organizers/logout',{method:'POST'});location.reload();}


let cachedCagnottes=[];let activeCagnotte=null;let cagPollTimer=null;
async function fetchPublicCagnottes(){try{const d=await api('/api/cagnottes');cachedCagnottes=d.cagnottes||[];renderPublicCagnottes();}catch(e){console.error(e)}}
function renderPublicCagnottes(){const grid=$('public-cagnottes-grid'),empty=$('public-cagnottes-empty');if(!grid)return;grid.innerHTML=cachedCagnottes.map(c=>{const imgs=Array.isArray(c.images)?c.images:[];const target=Number(c.target_amount||0),total=Number(c.total_amount||0),pct=target?Math.min(100,Math.round(total*100/target)):0;return `<article class="bg-white rounded-2xl border border-slate-200 overflow-hidden shadow-sm flex flex-col">${imgs.length?`<div class="w-full h-48 grid ${imgs.length>1?'grid-cols-2':''} gap-0 bg-slate-100">${imgs.slice(0,4).map((im,i)=>`<img src="${esc(im)}" class="w-full h-48 ${imgs.length>1?'object-cover':''}" alt="${esc(c.title)} ${i+1}">`).join('')}</div>`:`<div class="w-full h-48 bg-gradient-to-br from-[#071a3b] to-[#102d5e] flex items-center justify-center text-white text-4xl"><i class="fa-solid fa-hand-holding-heart"></i></div>`}<div class="p-5 flex-1"><div class="flex items-center justify-between gap-2"><span class="text-[10px] font-black uppercase bg-orange-50 text-[#F97316] px-2 py-1 rounded-full">Cagnotte</span><span class="text-xs text-emerald-600 font-bold">${fmt(total)} FCFA</span></div><h3 class="text-xl font-black text-[#071a3b] mt-3">${esc(c.title)}</h3><p class="text-sm text-slate-500 mt-2 line-clamp-4">${esc(c.description)}</p>${target?`<div class="mt-4"><div class="flex justify-between text-[10px] font-bold text-slate-500"><span>Collecté</span><span>${pct}%</span></div><div class="h-2 bg-slate-100 rounded-full overflow-hidden mt-1"><div class="h-full bg-[#F97316]" style="width:${pct}%"></div></div><div class="text-[10px] text-slate-400 mt-1">Objectif : ${fmt(target)} FCFA</div></div>`:''}</div><div class="p-5 pt-0"><button onclick="openCagnotteModal(${Number(c.id)})" class="w-full bg-[#F97316] hover:bg-orange-600 text-white font-bold py-3 rounded-xl">Contribuer</button></div></article>`}).join('');empty?.classList.toggle('hidden',cachedCagnottes.length>0)}
function openCagnotteModal(id){activeCagnotte=cachedCagnottes.find(c=>Number(c.id)===Number(id));if(!activeCagnotte)return;$('cag-modal-title').innerText=activeCagnotte.title;$('cag-modal-desc').innerText=activeCagnotte.description;$('cag-amount').value='';$('cag-name').value='';$('cag-email').value='';$('modal-cagnotte').classList.remove('hidden')}
function closeCagnotteModal(){if(cagPollTimer)clearInterval(cagPollTimer);$('modal-cagnotte')?.classList.add('hidden')}
async function contributeCagnotte(){if(!activeCagnotte)return;const amount=Number($('cag-amount').value),name=$('cag-name').value.trim(),email=$('cag-email').value.trim();if(!Number.isInteger(amount)||amount<100)return alert('Entrez un montant d’au moins 100 FCFA.');try{const d=await api(`/api/cagnottes/${activeCagnotte.id}/contribute`,{method:'POST',body:JSON.stringify({amount,name,email})});window.location.href=d.payment_url;}catch(e){alert(e.message)}}
function setupCagnotteReturn(){const q=new URLSearchParams(location.search);const token=q.get('token'),mode=q.get('cagnotte');if(!token||mode!=='return')return;showSection('client-home');$('modal-cagnotte')?.classList.remove('hidden');$('cag-modal-title').innerText='Confirmation de contribution';$('cag-modal-desc').innerText='Ticketora vérifie la confirmation réelle de votre paiement…';$('cag-name').value='';$('cag-email').value='';$('cag-amount').value='';let tries=0;cagPollTimer=setInterval(async()=>{tries++;try{const d=await api(`/api/cagnottes/contributions/${encodeURIComponent(token)}/status`);if(d.paid){clearInterval(cagPollTimer);$('cag-modal-desc').innerText='Merci ! Votre contribution a été confirmée.';$('cag-amount').value='';fetchPublicCagnottes();return}if(['cancelled','failed'].includes(d.status)||tries>=20){clearInterval(cagPollTimer);$('cag-modal-desc').innerText='Contribution non confirmée. Vous pouvez fermer cette fenêtre et réessayer.';}}catch(e){if(tries>=20){clearInterval(cagPollTimer);$('cag-modal-desc').innerText='Vérification impossible pour le moment.'}}},4000)}
window.fetchPublicCagnottes=fetchPublicCagnottes;window.openCagnotteModal=openCagnotteModal;window.closeCagnotteModal=closeCagnotteModal;window.contributeCagnotte=contributeCagnotte;
window.addEventListener('DOMContentLoaded',()=>{showSection('client-home');fetchPublicEvents();fetchPublicCagnottes();setupPaymentReturn();setupCagnotteReturn();checkOrgSession();});

window.showSection = showSection;

window.filterEvents = filterEvents;

window.closeBuyModal = closeBuyModal;

window.applyPromoCode = applyPromoCode;

window.downloadPDF = downloadPDF;

window.toggleOrgAuth = toggleOrgAuth;

window.switchOrgSection = switchOrgSection;

window.toggleEventForm = toggleEventForm;

window.addTicketCategoryRow = addTicketCategoryRow;
window.handleOrgLogin = handleOrgLogin;
window.handleOrgRegister = handleOrgRegister;
window.saveEvent = saveEvent;
window.requestPayout = requestPayout;
window.downloadOrgPayoutPDF = downloadOrgPayoutPDF;
window.scanTicketOrg = scanTicketOrg;
window.updateOrgPassword = updateOrgPassword;
window.logoutOrg = logoutOrg;
window.openBuyModal = openBuyModal;
window.processPayment = processPayment;
window.verifyTicketPublic = verifyTicketPublic;

window.deleteOrgEvent=deleteOrgEvent;window.deleteOrgPayout=deleteOrgPayout;


async function loadOrgPromos(){
  try{const d=await api('/api/organizers/promos');const el=$('org-promos-list');if(!el)return;el.innerHTML=(d.promos||[]).map(p=>{const used=Number(p.used_count||0),max=p.max_uses?Number(p.max_uses):null;const restriction=p.event_title||'Tous mes événements';const discount=p.discount_type==='PERCENT'?`${p.discount_value}%`:`${fmt(p.discount_value)} FCFA`;const status=p.active?'Actif':'Désactivé';return `<div class="p-4 border-b border-slate-100 flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div class="min-w-0"><div class="flex items-center gap-2 flex-wrap"><span class="font-mono font-black text-[#F97316] bg-orange-50 px-2 py-1 rounded-lg">${esc(p.code)}</span><span class="text-[10px] font-black uppercase px-2 py-1 rounded-full ${p.active?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}">${status}</span></div><p class="text-sm font-bold text-slate-800 mt-2">-${esc(discount)} • ${esc(restriction)}</p><p class="text-[11px] text-slate-400 mt-1">Utilisations : ${used}${max?` / ${max}`:' / illimité'} • Par client : ${Number(p.max_uses_per_customer)} • Min. : ${fmt(p.min_amount)} FCFA${p.allowed_ticket_types?.length?' • Billet(s) ciblé(s)':''}</p></div><div class="flex gap-2"><button onclick="toggleOrgPromo(${p.id})" class="px-3 py-2 rounded-lg text-xs font-bold ${p.active?'bg-amber-50 text-amber-700':'bg-emerald-50 text-emerald-700'}">${p.active?'Désactiver':'Activer'}</button><button onclick="viewPromoUsage(${p.id},'${esc(p.code)}')" class="px-3 py-2 rounded-lg bg-slate-100 text-slate-700 text-xs font-bold">Stats</button><button onclick="deleteOrgPromo(${p.id})" class="px-3 py-2 rounded-lg bg-red-50 text-red-600 text-xs font-bold">Supprimer</button></div></div>`}).join('')||'<div class="p-8 text-center text-sm text-slate-400">Aucun code promo créé.</div>';
  }catch(e){console.error(e)}}
async function createOrgPromo(e){e.preventDefault();const types=[...document.querySelectorAll('input[name="promo-ticket-type"]:checked')].map(x=>x.value);const body={code:$('promo-code').value,discountType:$('promo-discount-type').value,discountValue:$('promo-discount-value').value,eventId:$('promo-event').value||null,startsAt:$('promo-start').value?new Date($('promo-start').value).toISOString():null,endsAt:$('promo-end').value?new Date($('promo-end').value).toISOString():null,maxUses:$('promo-max-uses').value||null,maxUsesPerCustomer:$('promo-max-per-customer').value||1,minAmount:$('promo-min-amount').value||0,allowedTicketTypes:types};try{const d=await api('/api/organizers/promos',{method:'POST',body:JSON.stringify(body)});alert(d.message||'Code créé.');e.target.reset();$('promo-max-per-customer').value='1';loadOrgPromos();}catch(err){alert(err.message)}}
async function toggleOrgPromo(id){try{await api(`/api/organizers/promos/${id}/toggle`,{method:'POST'});loadOrgPromos();}catch(e){alert(e.message)}}
async function deleteOrgPromo(id){if(!confirm('Supprimer ce code promo ?'))return;try{await api(`/api/organizers/promos/${id}`,{method:'DELETE'});loadOrgPromos();}catch(e){alert(e.message)}}
async function viewPromoUsage(id,code){try{const d=await api(`/api/organizers/promos/${id}/usage`);const rows=d.usage||[];alert(`${code}\n\nUtilisations enregistrées : ${rows.length}\nRéductions accordées : ${fmt(rows.reduce((s,x)=>s+Number(x.discount_amount||0),0))} FCFA\n\n`+rows.slice(0,10).map(x=>`${x.customer_email} — ${fmt(x.discount_amount)} FCFA — ${x.order_status}`).join('\n'));}catch(e){alert(e.message)}}
async function populatePromoEvents(){const sel=$('promo-event');if(!sel)return;let events=window.orgEventsCache||[];if(!events.length){try{const d=await api('/api/organizers/events');events=d.events||[];window.orgEventsCache=events;}catch(e){console.error(e)}}sel.innerHTML='<option value="">Tous mes événements</option>'+events.map(e=>`<option value="${e.id}">${esc(e.title)}</option>`).join('');renderPromoTicketTypes();}
function renderPromoTicketTypes(){const box=$('promo-ticket-types'),sel=$('promo-event');if(!box)return;const events=window.orgEventsCache||[];const selected=sel?.value||'';let cats=[];if(selected){const e=events.find(x=>String(x.id)===String(selected));cats=Array.isArray(e?.ticket_categories)?e.ticket_categories:[];}else{cats=events.flatMap(e=>Array.isArray(e.ticket_categories)?e.ticket_categories:[]);}
const names=[...new Set(cats.map(c=>String(c.name||'').trim()).filter(Boolean))];box.innerHTML=names.map(name=>`<label class="inline-flex items-center gap-2 text-xs font-semibold text-slate-700 bg-slate-50 border border-slate-200 px-3 py-2 rounded-lg"><input type="checkbox" name="promo-ticket-type" value="${esc(name)}" class="accent-orange-500">${esc(name)}</label>`).join('')||'<span class="text-xs text-slate-400">Aucune catégorie disponible pour cette sélection.</span>';}

window.loadOrgPromos=loadOrgPromos;window.createOrgPromo=createOrgPromo;window.toggleOrgPromo=toggleOrgPromo;window.deleteOrgPromo=deleteOrgPromo;window.viewPromoUsage=viewPromoUsage;window.populatePromoEvents=populatePromoEvents;

async function loadOrgChat(){try{const d=await api('/api/organizers/chat/messages');const el=$('org-chat-messages');if(!el)return;el.innerHTML=(d.messages||[]).map(m=>`<div class="flex ${m.sender_role==='ORGANIZER'?'justify-end':'justify-start'}"><div class="max-w-[75%] rounded-2xl px-4 py-2 ${m.sender_role==='ORGANIZER'?'bg-[#F97316] text-white':'bg-white text-slate-800 border border-slate-200'}"><div class="text-sm whitespace-pre-wrap break-words">${esc(m.message)}</div><div class="text-[9px] opacity-60 mt-1">${new Date(m.created_at).toLocaleString('fr-FR')}</div></div></div>`).join('')||'<div class="text-center text-sm text-slate-400 mt-20">Aucun message. Écrivez à l’administration.</div>';el.scrollTop=el.scrollHeight;}catch(e){console.error(e)}}
async function sendOrgChat(e){e.preventDefault();const input=$('org-chat-input'),message=input.value.trim();if(!message)return;try{await api('/api/organizers/chat/messages',{method:'POST',body:JSON.stringify({message})});input.value='';await loadOrgChat();}catch(err){alert(err.message)}}
window.loadOrgChat=loadOrgChat;window.sendOrgChat=sendOrgChat;

async function loadScannerAgents(){try{const d=await api('/api/organizers/scanners');const el=$('org-scanners-list');if(!el)return;el.innerHTML=(d.scanners||[]).map(a=>`<div class="p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><div class="font-black text-slate-900">${esc(a.name||'Agent scanner')}</div><div class="font-mono text-sm text-[#F97316] mt-1">${esc(a.agent_number)}</div><div class="text-[10px] text-slate-400 mt-1">${a.active?'Actif':'Désactivé'}${a.last_login_at?' • Dernière connexion '+new Date(a.last_login_at).toLocaleString('fr-FR'):''}</div></div><div class="flex gap-2"><button onclick="toggleScannerAgent(${a.id})" class="px-3 py-2 rounded-lg text-xs font-bold ${a.active?'bg-amber-50 text-amber-700':'bg-emerald-50 text-emerald-700'}">${a.active?'Désactiver':'Activer'}</button><button onclick="deleteScannerAgent(${a.id})" class="px-3 py-2 rounded-lg bg-red-50 text-red-600 text-xs font-bold"><i class="fa-solid fa-trash"></i></button></div></div>`).join('')||'<div class="p-8 text-center text-sm text-slate-400">Aucun agent scanner.</div>';}catch(e){console.error(e);}}
async function createScannerAgent(e){e.preventDefault();try{const d=await api('/api/organizers/scanners',{method:'POST',body:JSON.stringify({name:$('scanner-agent-name').value,number:$('scanner-agent-number').value,password:$('scanner-agent-password').value})});alert(d.message||'Scanner créé.');e.target.reset();loadScannerAgents();}catch(err){alert(err.message)}}
async function toggleScannerAgent(id){try{await api(`/api/organizers/scanners/${id}/toggle`,{method:'POST'});loadScannerAgents();}catch(e){alert(e.message)}}
async function deleteScannerAgent(id){if(!confirm('Supprimer définitivement cet accès scanner ?'))return;try{await api(`/api/organizers/scanners/${id}`,{method:'DELETE'});loadScannerAgents();}catch(e){alert(e.message)}}
window.loadScannerAgents=loadScannerAgents;window.createScannerAgent=createScannerAgent;window.toggleScannerAgent=toggleScannerAgent;window.deleteScannerAgent=deleteScannerAgent;

