warning: in the working copy of 'app.js', LF will be replaced by CRLF the next time Git touches it
[1mdiff --git a/app.js b/app.js[m
[1mindex 39acb6b..5c6a4ad 100644[m
[1m--- a/app.js[m
[1m+++ b/app.js[m
[36m@@ -10,8 +10,8 @@[m [mfunction renderPublicEvents(){[m
  const grid=document.getElementById('all-events-grid')||document.getElementById('client-events-grid');[m
  const upcoming=document.getElementById('upcoming-events-grid');[m
  const empty=document.getElementById('upcoming-events-empty');[m
[31m- if(!grid&&!upcoming)return;[m
[31m- const card=e=>{let cats=Array.isArray(e.ticket_categories)?e.ticket_categories:[];const price=cats.length?Math.min(...cats.map(c=>Number(c.price||0))):Number(e.price||0);const free=String(e.event_type||'PAID')==='FREE';const sold=!!e.sold_out;const share=encodeURIComponent(`${location.origin}${location.pathname}?event=${e.id}`);return `<article class="event-card-public reveal bg-white rounded-2xl border border-slate-200 overflow-hidden flex flex-col shadow-sm relative group">${e.image_url?`<div class="relative overflow-hidden"><img src="${esc(e.image_url)}" alt="Affiche ${esc(e.title)}" class="w-full h-52 object-cover event-poster">${sold?'<span class="absolute top-4 left-4 bg-red-600 text-white px-3 py-1.5 rounded-lg text-xs font-black tracking-wide shadow-lg">SOLD OUT</span>':''}</div>`:`<div class="relative w-full h-52 bg-gradient-to-br from-[#071a3b] to-[#102d5e] flex items-center justify-center"><img src="logo.png" alt="Ticketora" class="w-20 h-20 object-contain opacity-80">${sold?'<span class="absolute top-4 left-4 bg-red-600 text-white px-3 py-1.5 rounded-lg text-xs font-black">SOLD OUT</span>':''}</div>`}<div class="p-5 flex flex-col flex-1"><div class="flex items-center justify-between gap-3"><span class="text-[10px] font-black uppercase bg-orange-50 text-[#F97316] border border-orange-100 px-2.5 py-1 rounded-full">${esc(e.category||'Événement')}</span><span class="text-xs text-slate-400 font-semibold"><i class="fa-regular fa-calendar mr-1"></i>${esc(e.date||'')}</span></div><h3 class="text-xl font-black text-[#071a3b] mt-3">${esc(e.title)}</h3><p class="text-xs text-slate-500 font-semibold mt-2"><i class="fa-solid fa-location-dot text-[#F97316] mr-1"></i>${esc(e.location||'')}</p><p class="text-sm text-slate-500 line-clamp-2 mt-3 flex-1">${esc(e.description||'')}</p><div class="flex items-center justify-between gap-3 border-t border-slate-100 mt-5 pt-4"><div><p class="text-[10px] uppercase font-black text-slate-400">${free?'ENTRÉE':'À PARTIR DE'}</p><p class="text-lg font-black text-[#071a3b]">${free?'GRATUITE':fmt(price)+' FCFA'}</p></div><div class="flex gap-2">${!sold?`<button onclick="openBuyModal(${Number(e.id)})" class="bg-[#F97316] hover:bg-orange-600 text-white font-bold px-4 py-2.5 rounded-xl text-xs transition">${free?'Participer':'Acheter'}</button>`:''}<button onclick="shareEvent(${Number(e.id)},'${share}')" class="w-10 h-10 border border-slate-200 rounded-xl text-slate-500 hover:text-[#F97316] transition" title="Partager"><i class="fa-solid fa-share-nodes"></i></button></div></div></div></article>`};[m
[32m+[m[32m if(!grid&&!upcoming)return;class="event-card-public  bg-white rounded-2xl border border-slate-200 overflow-hidden flex flex-col shadow-sm relative group"[m
[32m+[m[32m const card=e=>{let cats=Array.isArray(e.ticket_categories)?e.ticket_categories:[];const price=cats.length?Math.min(...cats.map(c=>Number(c.price||0))):Number(e.price||0);const free=String(e.event_type||'PAID')==='FREE';const sold=!!e.sold_out;const share=encodeURIComponent(`${location.origin}${location.pathname}?event=${e.id}`);return `<article >${e.image_url?`<div class="relative overflow-hidden"><img src="${esc(e.image_url)}" alt="Affiche ${esc(e.title)}" class="w-full h-52 object-cover event-poster">${sold?'<span class="absolute top-4 left-4 bg-red-600 text-white px-3 py-1.5 rounded-lg text-xs font-black tracking-wide shadow-lg">SOLD OUT</span>':''}</div>`:`<div class="relative w-full h-52 bg-gradient-to-br from-[#071a3b] to-[#102d5e] flex items-center justify-center"><img src="logo.png" alt="Ticketora" class="w-20 h-20 object-contain opacity-80">${sold?'<span class="absolute top-4 left-4 bg-red-600 text-white px-3 py-1.5 rounded-lg text-xs font-black">SOLD OUT</span>':''}</div>`}<div class="p-5 flex flex-col flex-1"><div class="flex items-center justify-between gap-3"><span class="text-[10px] font-black uppercase bg-orange-50 text-[#F97316] border border-orange-100 px-2.5 py-1 rounded-full">${esc(e.category||'Événement')}</span><span class="text-xs text-slate-400 font-semibold"><i class="fa-regular fa-calendar mr-1"></i>${esc(e.date||'')}</span></div><h3 class="text-xl font-black text-[#071a3b] mt-3">${esc(e.title)}</h3><p class="text-xs text-slate-500 font-semibold mt-2"><i class="fa-solid fa-location-dot text-[#F97316] mr-1"></i>${esc(e.location||'')}</p><p class="text-sm text-slate-500 line-clamp-2 mt-3 flex-1">${esc(e.description||'')}</p><div class="flex items-center justify-between gap-3 border-t border-slate-100 mt-5 pt-4"><div><p class="text-[10px] uppercase font-black text-slate-400">${free?'ENTRÉE':'À PARTIR DE'}</p><p class="text-lg font-black text-[#071a3b]">${free?'GRATUITE':fmt(price)+' FCFA'}</p></div><div class="flex gap-2">${!sold?`<button onclick="openBuyModal(${Number(e.id)})" class="bg-[#F97316] hover:bg-orange-600 text-white font-bold px-4 py-2.5 rounded-xl text-xs transition">${free?'Participer':'Acheter'}</button>`:''}<button onclick="shareEvent(${Number(e.id)},'${share}')" class="w-10 h-10 border border-slate-200 rounded-xl text-slate-500 hover:text-[#F97316] transition" title="Partager"><i class="fa-solid fa-share-nodes"></i></button></div></div></div></article>`};[m
  const cards=(cachedEvents||[]).map(card).join('');[m
  if(grid)grid.innerHTML=cards||'<p class="text-slate-500 text-sm font-semibold">Aucun événement publié.</p>';[m
  if(upcoming){const upcomingEvents=(cachedEvents||[]).slice(0,3);upcoming.innerHTML=upcomingEvents.map(card).join('');if(empty)empty.classList.toggle('hidden',upcomingEvents.length>0);}[m
[36m@@ -127,7 +127,11 @@[m [mfunction initV3Animations(){const obs=new IntersectionObserver(es=>es.forEach(e=[m
 async function participantAuth(mode){const email=document.getElementById('participant-email')?.value.trim(),password=document.getElementById('participant-password')?.value||'',name=document.getElementById('participant-name')?.value.trim();try{const d=await api(mode==='register'?'/api/participants/register':'/api/participants/login',{method:'POST',body:JSON.stringify(mode==='register'?{name,email,password}:{email,password})});if(d.success){closeParticipantModal();showParticipantHistory();}}catch(e){alert(e.message)}}[m
 async function showParticipantHistory(){try{const d=await api('/api/participants/history');const t=(d.tickets||[]).map(x=>`<div class="bg-white border rounded-2xl p-4"><div class="flex justify-between gap-3"><b>${esc(x.event_title)}</b><span class="text-xs font-bold ${x.used?'text-slate-400':'text-emerald-600'}">${x.used?'VALIDÉ':'VALIDE'}</span></div><p class="text-sm text-slate-500 mt-1">${esc(x.ticket_type)} · ${esc(x.code)}</p><button onclick="window.open(API+'/api/tickets/'+encodeURIComponent('${x.code}')+'/qr','_blank')" class="mt-3 text-xs font-bold text-[#F97316]">QR Code</button></div>`).join('');let box=document.getElementById('participant-history-box');if(!box){box=document.createElement('div');box.id='participant-history-box';box.className='fixed inset-0 z-[90] bg-black/70 backdrop-blur-sm p-4 overflow-auto';document.body.appendChild(box);}box.innerHTML=`<div class="max-w-2xl mx-auto mt-10 bg-slate-50 rounded-3xl p-6"><div class="flex justify-between items-center"><h2 class="text-2xl font-black text-[#071a3b]">Mon historique</h2><button onclick="this.closest('#participant-history-box').remove()" class="text-slate-400 text-xl">×</button></div><div class="space-y-3 mt-5">${t||'<p class="text-slate-500">Aucun billet associé à ce compte.</p>'}</div></div>`;}catch(e){alert(e.message)}}[m
 function downloadCSV(path){window.open(API+path,'_blank');}[m
[31m-document.addEventListene